### ISSUE TITLE
issue with ax.get_next_trial()?

### ISSUE THREAD

**Issue by kang985** [facebook/Ax#1016]
I'm totally new to Ax and BoTorch. While I was going thru these tutorials:
https://ax.dev/tutorials/gpei_hartmann_service.html
https://botorch.org/tutorials/custom_botorch_model_in_ax

I ran into an error: TypeError: __init__() got an unexpected keyword argument 'environmental_variables'
I found out this error occurs whenever I call **.get_next_trial()** (e.g., in 4. Run optimization loop in the first tutorial above) or **.new_trial()** (e.g., in Run the BO loop under the 'Optimization with the Developer API Section' in the second tutorial above).

But I was able to run BoTorch without Ax, e.g., as in this BoTorch tutorial: https://botorch.org/tutorials/closed_loop_botorch_only
And so I guess this is an ax specific issue or an issue with my environment. 

I'm working with MacBook Pro 2019 (16 in), with Python 3.8.2. and Pycharm 2022.1.2. (Prof Ed)
Any help to solve this issue would be much appreciated!

**Comment by kang985** [comment]
Thank you for the reply. Here's the printed traceback I got when I downloaded the tutorial source code (custom_botorch_model_in_ax.py) in this link and just ran it: https://botorch.org/tutorials/custom_botorch_model_in_ax. It seems the script works okay until Line 244.


[INFO 07-05 14:04:32] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 07-05 14:04:32] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter x1. If that is not the expected value type, you can explicity specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 07-05 14:04:32] ax.service.utils.instantiation: Inferred value type of ParameterType.FLOAT for parameter x2. If that is not the expected value type, you can explicity specify 'value_type' ('int', 'float', 'bool' or 'str') in parameter dict.
[INFO 07-05 14:04:32] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[RangeParameter(name='x1', parameter_type=FLOAT, range=[-5.0, 10.0]), RangeParameter(name='x2', parameter_type=FLOAT, range=[0.0, 15.0])], parameter_constraints=[]).
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 247, in <module>
  File "/Users/kang985/PycharmProjects/Tutorials/venv/src/ax-platform/ax/utils/common/executils.py", line 147, in actual_wrapper
    return func(*args, **kwargs)
  File "/Users/kang985/PycharmProjects/Tutorials/venv/lib/python3.8/site-packages/ax/service/ax_client.py", line 466, in get_next_trial
    generator_run=self._gen_new_generator_run(), ttl_seconds=ttl_seconds
  File "/Users/kang985/PycharmProjects/Tutorials/venv/lib/python3.8/site-packages/ax/service/ax_client.py", line 1551, in _gen_new_generator_run
    return not_none(self.generation_strategy).gen(
  File "/Users/kang985/PycharmProjects/Tutorials/venv/lib/python3.8/site-packages/ax/modelbridge/generation_strategy.py", line 332, in gen
    return self._gen_multiple(
  File "/Users/kang985/PycharmProjects/Tutorials/venv/lib/python3.8/site-packages/ax/modelbridge/generation_strategy.py", line 473, in _gen_multiple
    generator_run = _gen_from_generation_step(
  File "/Users/kang985/PycharmProjects/Tutorials/venv/lib/python3.8/site-packages/ax/modelbridge/generation_strategy.py", line 835, in _gen_from_generation_step
    generator_run = generation_step.gen(
  File "/Users/kang985/PycharmProjects/Tutorials/venv/lib/python3.8/site-packages/ax/modelbridge/generation_node.py", line 165, in gen
    return model_spec.gen(
  File "/Users/kang985/PycharmProjects/Tutorials/venv/lib/python3.8/site-packages/ax/modelbridge/model_spec.py", line 204, in gen
    return fitted_model.gen(**model_gen_kwargs)
  File "/Users/kang985/PycharmProjects/Tutorials/venv/src/ax-platform/ax/modelbridge/base.py", line 667, in gen
    gen_results = self._gen(
  File "/Users/kang985/PycharmProjects/Tutorials/venv/lib/python3.8/site-packages/ax/modelbridge/random.py", line 79, in _gen
    search_space_digest = extract_search_space_digest(search_space, self.parameters)
  File "/Users/kang985/PycharmProjects/Tutorials/venv/lib/python3.8/site-packages/ax/modelbridge/modelbridge_utils.py", line 134, in extract_search_space_digest
    return SearchSpaceDigest(
TypeError: __init__() got an unexpected keyword argument 'environmental_variables'

**Comment by mpolson64** [comment]
Thank you for providing the stack trace, this was informative. I am still having trouble reproducing, could I ask what versions of both Ax and Botorch you're using, and if you're seeing this same error when running the Ax tutorial you linked here https://ax.dev/tutorials/gpei_hartmann_service.html ?
I suspect you may be using a version of Ax incompatible with the published botorch tutorials. While we work closely with the Botorch team, there are times when the latest Botorch, latest Ax, and their respective tutorials may become out of date with each other. We test the Ax tutorials on the most recent stable version of Ax (0.2.5) with a pinned version of botorch (0.6.4), and when I do this on my end it looks like things pass; could you be using newer versions of either package? Let me know if you were using some other versions of Ax and Botorch when you received this error, and if changing back to the stable releases of both allows you to run the tutorial I linked above.
Sorry this has caused some difficultly -- I'm hoping we can get you up and running soon!

**Comment by kang985** [comment]
Hi again!
I'm using botorch (0.6.4) and Ax (0.2.5.1) installed through the PyCharm package manager. I tried deleting Ax and examining an older version Ax (0.2.4), but this did not resolve the issue.

And yes, I run into the same issue when I run the Ax tutorial you mentioned. Specifically, get_next_trial() in Line 116 produces the same error. Plus, init_notebook_plotting() in Line 21 also produces the following error:

--
[INFO 07-05 17:46:16] ax.utils.notebook.plotting: Injecting Plotly library into cell. Do not overwrite or delete cell.
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/kih1007/PycharmProjects/Tutorials/venv/src/ax-platform/ax/utils/notebook/plotting.py", line 22, in init_notebook_plotting
    init_notebook_mode()
  File "/Users/kih1007/PycharmProjects/Tutorials/venv/lib/python3.8/site-packages/plotly/offline/offline.py", line 292, in init_notebook_mode
    pio.renderers._activate_pending_renderers()
  File "/Users/kih1007/PycharmProjects/Tutorials/venv/lib/python3.8/site-packages/plotly/io/_renderers.py", line 192, in _activate_pending_renderers
    renderer.activate()
  File "/Users/kih1007/PycharmProjects/Tutorials/venv/lib/python3.8/site-packages/plotly/io/_base_renderers.py", line 273, in activate
    raise ValueError(
ValueError: The NotebookRenderer class requires ipython but it is not installed
--

It's saying that I do not have ipython installed, but I have ipython 8.4.0 installed. 

Could it be related to PyCharm in any sense?

Thank you again for your help!

**Comment by mpolson64** [comment]
> Could it be related to PyCharm in any sense?

This seems like it may be the case. I am not familiar with the PyCharm package manager; most of our users install via pip3 which should handle the installation of all dependencies neatly out of the box. Is there a way to get a `pip freeze` of the python environment PyCharm has created so we can take a look?

If you'd rather, perhaps the quickest way to get things working would be to install with pip following the commands on our website and seeing if the Ax tutorial runs on your environment then. Whichever you would perfer.

cc @danielcohenlive

**Comment by kang985** [comment]
Thank you again for the reply! I was not able to solve this issue yet, and ended up using BoTorch without Ax to run my stuff.
Regardless, I appreciate your trying to help me and resolve the issue!
