### ISSUE TITLE
[Error] When optimizer changes from SOBOL to GPEI I get Assertion Error

### ISSUE THREAD

**Issue by JonAnderRuizColmenares** [facebook/Ax#1564]
Hi, 

I am trying to optimize a Neural Network for regression, my search space is as follows:
```
parameters=[
    {
        "name": "learning_rate",
        "type": "range",
        "bounds": [0.00001, 0.1],
        "value_type": "float",
        "log_scale": True,
    },
    {
        "name": "momentum",
        "type": "range",
        "bounds": [0.00001, 1],
        "value_type": "float",
        "log_scale": False,
    },
    {
        "name": "Dense_0",
        "type": "choice",
        "value_type": "int",
        "values": [8, 16, 32, 64, 128, 256, 512, 1024],
        "is_ordered": True, 
    },
    {
        "name": "Dropout_0",
        "type": "range",
        "bounds": [0.01, 0.8],
        "value_type": "float",
        "log_scale": False,
    },
    {
        "name": "LayerNumber",
        "type": "choice",
        "value_type": "int",
        "values": [0,1,2],
        "is_ordered": False, 
    },
    {
        "name": "Dense_1",
        "type": "choice",
        "value_type": "int",
        "values": [8, 16, 32, 64, 128, 256, 512, 1024],
        "is_ordered": True, 
    },
    {
        "name": "Dropout_1",
        "type": "range",
        "bounds": [0.01, 0.8],
        "value_type": "float",
        "log_scale": False,
    },
    {
        "name": "Dense_2",
        "type": "choice",
        "value_type": "int",
        "values": [8, 16, 32, 64, 128, 256, 512, 1024],
        "is_ordered": True, 
    },
    {
        "name": "Dropout_2",
        "type": "range",
        "bounds": [0.01, 0.8],
        "value_type": "float",
        "log_scale": False,
    },]
```

My evaluation function is as follows: It gets the data from 'get_data_UNBE2203()', trains a Neural Network and then calculates a R2 parameter for optimization.
```
def compute_NN(parameters, graph=False):
    
    df_completo, X_train, X_test, y_train, y_test = get_data_UNBE2203()

    inputVariables = X_train.shape[1]
    
    model = Sequential()
    
    model.add(Dense(parameters['Dense_0'], input_dim=inputVariables, activation='relu'))
    model.add(Dropout(parameters['Dropout_1']))

    layerChoice = parameters['LayerNumber']
    
    if layerChoice > 0:
        model.add(Dropout(parameters['Dropout_1']))
        model.add(Dense(parameters['Dense_1'], activation='relu'))
    if layerChoice > 1:
        model.add(Dropout(parameters['Dropout_2']))
        model.add(Dense(parameters['Dense_2'], activation='relu'))

    model.add(Dense(1, activation='linear'))
    
    opt = SGD(learning_rate=parameters['learning_rate'], momentum=parameters['momentum'])
    model.compile(loss='mean_squared_error', optimizer=opt)
    
    # fit model
    history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, verbose=0)

    pred = model.predict(X_test)
    coefficient_of_dermination = r2_score(y_test, pred)
    r2 = coefficient_of_dermination

    return r2
```

My optimization loop:
```
best_parameters, best_values, experiment, model = optimize(
    
    parameters,
    evaluation_function=compute_NN,
    minimize=False,
    total_trials=30,
    )    
```

Its pretty straightforward, I have used some Ax templates and forum posts to build it. When I train it, the first 18 iterations of the optimizer work perfectly, but then I get the following error (when GPEI starts being used instead of Sobol)

```
[ERROR 04-03 10:28:53] ax.service.managed_loop: Encountered exception during optimization: 
Traceback (most recent call last):
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\utils\common\serialization.py", line 54, in callable_to_reference
    assert pydoc.locate(name) is callable
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\service\managed_loop.py", line 227, in full_run
    self.run_trial()
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\utils\common\executils.py", line 161, in actual_wrapper
    return func(*args, **kwargs)
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\service\managed_loop.py", line 201, in run_trial
    trial = self._get_new_trial()
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\service\managed_loop.py", line 159, in _get_new_trial
    generator_run=self.generation_strategy.gen(
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\modelbridge\generation_strategy.py", line 335, in gen
    return self._gen_multiple(
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\modelbridge\generation_strategy.py", line 458, in _gen_multiple
    self._fit_or_update_current_model(data=data)
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\modelbridge\generation_strategy.py", line 514, in _fit_or_update_current_model
    self._fit_current_model(data=self._get_data_for_fit(passed_in_data=data))
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\modelbridge\generation_strategy.py", line 675, in _fit_current_model
    self._curr.fit(experiment=self.experiment, data=data, **model_state_on_lgr)
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\modelbridge\generation_node.py", line 129, in fit
    model_spec.fit(  # Stores the fitted model as `model_spec._fitted_model`
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\modelbridge\model_spec.py", line 128, in fit
    self._fitted_model = self.model_enum(
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\modelbridge\registry.py", line 365, in __call__
    model_kwargs=_encode_callables_as_references(model_kwargs),
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\modelbridge\registry.py", line 561, in _encode_callables_as_references
    return {
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\modelbridge\registry.py", line 562, in <dictcomp>
    k: {"is_callable_as_path": True, "value": callable_to_reference(v)}
  File "C:\Users\811632\Anaconda3\envs\Anaconda3_python1\lib\site-packages\ax\utils\common\serialization.py", line 57, in callable_to_reference
    raise TypeError(
TypeError: Callable get_and_fit_model is not properly exposed in ax.models.torch.botorch_defaults (exception: ).
```

I have used pretty much this template for other optimizations and calculations and I have never encountered this error, I am pretty confused as to what I am doing wrong or if I need to specify something so that GPEI doesnt crash.

Any help would be appreciated.

**Comment by JonAnderRuizColmenares** [comment]
It seemed like after that error every script was crashing when changing to GPEI. After restarting everything I went to check and found that everything had solved itself... I will try to reproduce the conditions that led to the error. 

The packages I have are these, sorry for the mess its a test environment.

```
absl-py==1.4.0Note: you may need to restart the kernel to use updated packages.
aiohttp==3.8.1
aiosignal==1.2.0
alabaster @ file:///home/ktietz/src/ci/alabaster_1611921544520/work
anaconda-client==1.7.2
anaconda-navigator==2.1.2
anaconda-project @ file:///tmp/build/80754af9/anaconda-project_1610472525955/work

anyio @ file:///C:/ci/anyio_1620153418380/work/dist
appdirs==1.4.4
argh==0.26.2
argon2-cffi @ file:///C:/ci/argon2-cffi_1613037959010/work
asn1crypto @ file:///tmp/build/80754af9/asn1crypto_1596577642040/work
astroid @ file:///C:/ci/astroid_1613501047216/work
astropy @ file:///C:/ci/astropy_1617745647203/work
astunparse==1.6.3
async-generator @ file:///home/ktietz/src/ci/async_generator_1611927993394/work
async-timeout==4.0.1
atomicwrites==1.4.0
attrs @ file:///tmp/build/80754af9/attrs_1604765588209/work
autopep8 @ file:///tmp/build/80754af9/autopep8_1615918855173/work
ax-platform==0.2.9
Babel @ file:///tmp/build/80754af9/babel_1607110387436/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
backports.functools-lru-cache @ file:///tmp/build/80754af9/backports.functools_lru_cache_1618170165463/work
backports.shutil-get-terminal-size @ file:///tmp/build/80754af9/backports.shutil_get_terminal_size_1608222128777/work
backports.tempfile @ file:///home/linux1/recipes/ci/backports.tempfile_1610991236607/work
backports.weakref==1.0.post1
bcrypt @ file:///C:/ci/bcrypt_1597936263757/work
beautifulsoup4 @ file:///home/linux1/recipes/ci/beautifulsoup4_1610988766420/work
bitarray @ file:///C:/ci/bitarray_1618435038389/work
bkcharts==0.2
black==19.10b0
bleach @ file:///tmp/build/80754af9/bleach_1612211392645/work
bokeh @ file:///C:/ci/bokeh_1620784067744/work
boto==2.49.0
botorch==0.7.2
Bottleneck==1.3.2
Brotli==1.0.9
brotlipy==0.7.0
cachetools==5.0.0
certifi==2021.10.8
cffi @ file:///C:/ci/cffi_1613247279197/work
chardet @ file:///C:/ci/chardet_1607690654534/work
charset-normalizer==2.0.9
click @ file:///home/linux1/recipes/ci/click_1610990599742/work
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1598884132938/work
clyent==1.2.2
colorama @ file:///tmp/build/80754af9/colorama_1607707115595/work
colourmap==0.1.1
comtypes==1.1.9
conda==4.11.0
conda-build==3.21.4
conda-content-trust @ file:///tmp/build/80754af9/conda-content-trust_1617045594566/work
conda-package-handling @ file:///C:/ci/conda-package-handling_1618262320430/work
conda-repo-cli @ file:///tmp/build/80754af9/conda-repo-cli_1620168426516/work
conda-token @ file:///tmp/build/80754af9/conda-token_1620076980546/work
conda-verify==3.4.2
contextlib2==0.6.0.post1
cryptography @ file:///C:/ci/cryptography_1616769344312/work
cssselect2==0.7.0
cycler==0.10.0
Cython @ file:///C:/ci/cython_1618435363327/work
cytoolz==0.11.0
dask @ file:///tmp/build/80754af9/dask-core_1617390489108/work
dataframe-image==0.1.1
decorator @ file:///tmp/build/80754af9/decorator_1617916966915/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
diff-match-patch @ file:///tmp/build/80754af9/diff-match-patch_1594828741838/work
distributed @ file:///C:/ci/distributed_1617384289923/work
docutils @ file:///C:/ci/docutils_1617481617511/work
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
filelock @ file:///home/linux1/recipes/ci/filelock_1610993975404/work
flake8 @ file:///tmp/build/80754af9/flake8_1615834841867/work
Flask @ file:///home/ktietz/src/ci/flask_1611932660458/work
flatbuffers==23.3.3
fonttools==4.37.3
frozenlist==1.2.0
fsspec @ file:///tmp/build/80754af9/fsspec_1617959894824/work
future==0.18.2
gast==0.4.0
gevent @ file:///C:/ci/gevent_1616773090559/work
glob2 @ file:///home/linux1/recipes/ci/glob2_1610991677669/work
gmpy2 @ file:///C:/ci/gmpy2_1645456279018/work
google-api-core==2.5.0
google-api-python-client==2.36.0
google-auth==2.6.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
googleapis-common-protos==1.54.0
gpytorch==1.9.0
greenlet @ file:///C:/ci/greenlet_1611958565931/work
grpcio==1.53.0
h5py==2.10.0
HeapDict==1.0.1
heatmapz==0.0.4
hid==1.0.4
hidapi==0.11.0.post2
html5lib @ file:///tmp/build/80754af9/html5lib_1593446221756/work
httplib2==0.20.4
idna @ file:///home/linux1/recipes/ci/idna_1610986105248/work
imagecodecs @ file:///C:/ci/imagecodecs_1617996768495/work
imageio @ file:///tmp/build/80754af9/imageio_1617700267927/work
imagesize @ file:///Users/ktietz/demo/mc3/conda-bld/imagesize_1628863108022/work
imbalanced-learn==0.8.1
imgkit==1.2.2
importlib-metadata==6.1.0
iniconfig @ file:///home/linux1/recipes/ci/iniconfig_1610983019677/work
intervaltree @ file:///tmp/build/80754af9/intervaltree_1598376443606/work
ipykernel @ file:///C:/ci/ipykernel_1596190155316/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython @ file:///C:/ci/ipython_1617121002983/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1610481889018/work
isort @ file:///tmp/build/80754af9/isort_1616355431277/work
itsdangerous @ file:///home/ktietz/src/ci/itsdangerous_1611932585308/work
jax==0.4.8
jdcal==1.4.1
jedi @ file:///C:/ci/jedi_1606914528444/work
Jinja2 @ file:///tmp/build/80754af9/jinja2_1612213139570/work
joblib @ file:///tmp/build/80754af9/joblib_1613502643832/work
json5==0.9.5
jsonschema @ file:///tmp/build/80754af9/jsonschema_1602607155483/work
jupyter==1.0.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1616770841739/work
jupyter-console @ file:///tmp/build/80754af9/jupyter_console_1616615302928/work
jupyter-core @ file:///C:/ci/jupyter_core_1612213356021/work
jupyter-packaging @ file:///tmp/build/80754af9/jupyter-packaging_1613502826984/work
jupyter-server @ file:///C:/ci/jupyter_server_1616084298403/work
jupyterlab @ file:///tmp/build/80754af9/jupyterlab_1619133235951/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-server @ file:///tmp/build/80754af9/jupyterlab_server_1617134334258/work
jupyterlab-widgets @ file:///tmp/build/80754af9/jupyterlab_widgets_1609884341231/work
keras==2.12.0
keyring @ file:///C:/ci/keyring_1614616910860/work
kiwisolver @ file:///C:/ci/kiwisolver_1612282606037/work
lazy-object-proxy @ file:///C:/ci/lazy-object-proxy_1616529307648/work
libarchive-c @ file:///tmp/build/80754af9/python-libarchive-c_1617780486945/work
libclang==16.0.0
linear-operator==0.1.1
llvmlite==0.36.0
locket==0.2.1
lxml @ file:///C:/ci/lxml_1616443455957/work
Markdown==3.4.3
MarkupSafe==1.1.1
matplotlib @ file:///C:/ci/matplotlib-suite_1613408055530/work
mccabe==0.6.1
menuinst==1.4.16
mistune==0.8.4
mkl-fft==1.3.0
mkl-random @ file:///C:/ci/mkl_random_1618854156666/work
mkl-service==2.3.0
ml-dtypes==0.0.4
mock @ file:///tmp/build/80754af9/mock_1607622725907/work
more-itertools @ file:///tmp/build/80754af9/more-itertools_1613676688952/work
mpmath==1.2.1
msgpack @ file:///C:/ci/msgpack-python_1612287368835/work
multidict==5.2.0
multipledispatch==0.6.0
mypy-extensions==0.4.3
navigator-updater==0.2.1
nbclassic @ file:///tmp/build/80754af9/nbclassic_1616085367084/work
nbclient @ file:///tmp/build/80754af9/nbclient_1614364831625/work
nbconvert @ file:///C:/ci/nbconvert_1601914925608/work
nbformat @ file:///tmp/build/80754af9/nbformat_1617383369282/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1613680548246/work
networkx @ file:///tmp/build/80754af9/networkx_1598376031484/work
nltk @ file:///tmp/build/80754af9/nltk_1618327084230/work
nose @ file:///tmp/build/80754af9/nose_1606773131901/work
notebook @ file:///C:/ci/notebook_1616443715883/work
numba @ file:///C:/ci/numba_1616774458845/work
numexpr @ file:///C:/ci/numexpr_1618856738664/work
numpy==1.23.5
numpydoc @ file:///tmp/build/80754af9/numpydoc_1605117425582/work
oauth2client==4.1.3
oauthlib==3.2.2
olefile==0.46
openpyxl @ file:///tmp/build/80754af9/openpyxl_1615411699337/work
opt-einsum==3.3.0
packaging @ file:///tmp/build/80754af9/packaging_1611952188834/work
pandas @ file:///C:/ci/pandas_1618365634936/work
pandocfilters @ file:///C:/ci/pandocfilters_1605102497129/work
paramiko @ file:///tmp/build/80754af9/paramiko_1598886428689/work
parso==0.7.0
partd @ file:///tmp/build/80754af9/partd_1618000087440/work
path @ file:///C:/ci/path_1614022440181/work
pathlib2 @ file:///C:/ci/pathlib2_1607025069150/work
pathspec==0.7.0
pathtools @ file:///Users/ktietz/demo/mc3/conda-bld/pathtools_1629713893697/work
patsy==0.5.1
pca==1.6.2
pep8==1.7.1
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow @ file:///C:/ci/pillow_1617386341487/work
pkginfo==1.7.0
plotly==5.11.0
pluggy @ file:///C:/ci/pluggy_1615976358795/work
ply==3.11
prometheus-client @ file:///tmp/build/80754af9/prometheus_client_1618088486455/work
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1616415428029/work
protobuf==4.22.1
psutil @ file:///C:/ci/psutil_1612298324802/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
py @ file:///tmp/build/80754af9/py_1607971587848/work
pyarrow==7.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle @ file:///home/ktietz/src/ci_mi/pycodestyle_1612807597675/work
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pycurl==7.43.0.6
pydocstyle @ file:///tmp/build/80754af9/pydocstyle_1616182067796/work
PyDrive==1.3.1
pydyf==0.3.0
pyerfa @ file:///C:/ci/pyerfa_1619391071834/work
pyflakes @ file:///home/ktietz/src/ci_ipy2/pyflakes_1612551159640/work
Pygments @ file:///tmp/build/80754af9/pygments_1615143339740/work
PyJWT @ file:///C:/ci/pyjwt_1619651841937/work
pylint @ file:///C:/ci/pylint_1617136058775/work
pyls-black @ file:///tmp/build/80754af9/pyls-black_1607553132291/work
pyls-spyder @ file:///tmp/build/80754af9/pyls-spyder_1613849700860/work
PyNaCl @ file:///C:/ci/pynacl_1595000047588/work
pyodbc===4.0.0-unsupported
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing @ file:///home/linux1/recipes/ci/pyparsing_1610983426697/work
pyphen==0.13.0
pyreadline==2.1
pyro-api==0.1.2
pyro-ppl==1.8.2
pyrsistent @ file:///C:/ci/pyrsistent_1600141795814/work
PySocks @ file:///C:/ci/pysocks_1605287845585/work
pytest==6.2.3
pytest-runner @ file:///tmp/build/80754af9/pytest-runner_1623663836848/work
python-dateutil @ file:///home/ktietz/src/ci/python-dateutil_1611928101742/work
python-jsonrpc-server @ file:///tmp/build/80754af9/python-jsonrpc-server_1600278539111/work
python-language-server @ file:///tmp/build/80754af9/python-language-server_1607972495879/work
pytz @ file:///tmp/build/80754af9/pytz_1612215392582/work
PyWavelets @ file:///C:/ci/pywavelets_1601658407916/work
pywin32==227
pywin32-ctypes==0.2.0
pywinpty==0.5.7
PyYAML==5.4.1
pyzmq==20.0.0
QDarkStyle==2.8.1
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1615991616277/work
qtconsole @ file:///tmp/build/80754af9/qtconsole_1616775094278/work
QtPy==1.9.0
regex @ file:///C:/ci/regex_1617569893741/work
requests @ file:///tmp/build/80754af9/requests_1608241421344/work
requests-oauthlib==1.3.1
rope @ file:///tmp/build/80754af9/rope_1602264064449/work
rsa==4.8
Rtree @ file:///C:/ci/rtree_1618421009405/work
ruamel-yaml-conda @ file:///C:/ci/ruamel_yaml_1616016967756/work
scikit-image==0.18.1
scikit-learn==1.0.1
scipy==1.10.1
seaborn @ file:///tmp/build/80754af9/seaborn_1608578541026/work
Send2Trash @ file:///tmp/build/80754af9/send2trash_1607525499227/work
simplegeneric==0.8.1
singledispatch @ file:///tmp/build/80754af9/singledispatch_1614366001199/work
sip==4.19.13
six @ file:///C:/ci/six_1605187374963/work
sklearn==0.0
sniffio @ file:///C:/ci/sniffio_1614030707456/work
snowballstemmer @ file:///tmp/build/80754af9/snowballstemmer_1611258885636/work
sortedcollections @ file:///tmp/build/80754af9/sortedcollections_1611172717284/work
sortedcontainers @ file:///tmp/build/80754af9/sortedcontainers_1606865132123/work
soupsieve @ file:///tmp/build/80754af9/soupsieve_1616183228191/work
Sphinx @ file:///tmp/build/80754af9/sphinx_1620777493457/work
sphinxcontrib-applehelp @ file:///home/ktietz/src/ci/sphinxcontrib-applehelp_1611920841464/work
sphinxcontrib-devhelp @ file:///home/ktietz/src/ci/sphinxcontrib-devhelp_1611920923094/work
sphinxcontrib-htmlhelp @ file:///home/ktietz/src/ci/sphinxcontrib-htmlhelp_1611920974801/work
sphinxcontrib-jsmath @ file:///home/ktietz/src/ci/sphinxcontrib-jsmath_1611920942228/work
sphinxcontrib-qthelp @ file:///home/ktietz/src/ci/sphinxcontrib-qthelp_1611921055322/work
sphinxcontrib-serializinghtml @ file:///home/ktietz/src/ci/sphinxcontrib-serializinghtml_1611920755253/work
sphinxcontrib-websupport @ file:///tmp/build/80754af9/sphinxcontrib-websupport_1597081412696/work
spyder @ file:///C:/ci/spyder_1616776239898/work
spyder-kernels @ file:///C:/ci/spyder-kernels_1614030842607/work
SQLAlchemy @ file:///C:/ci/sqlalchemy_1618090063261/work
statsmodels==0.12.2
sympy @ file:///C:/ci/sympy_1618255511605/work
tables==3.6.1
tblib @ file:///tmp/build/80754af9/tblib_1597928476713/work
tenacity==8.1.0
tensorboard==2.12.0
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
tensorflow==2.12.0
tensorflow-estimator==2.12.0
tensorflow-intel==2.12.0
tensorflow-io-gcs-filesystem==0.31.0
termcolor==2.2.0
terminado==0.9.4
testpath @ file:///home/ktietz/src/ci/testpath_1611930608132/work
textdistance @ file:///tmp/build/80754af9/textdistance_1612461398012/work
threadpoolctl @ file:///tmp/tmp9twdgx9k/threadpoolctl-2.1.0-py3-none-any.whl
three-merge @ file:///tmp/build/80754af9/three-merge_1607553261110/work
tifffile @ file:///tmp/build/80754af9/tifffile_1619636090847/work
tinycss2==1.1.1
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
toolz @ file:///home/linux1/recipes/ci/toolz_1610987900194/work
torch==1.13.0
tornado @ file:///C:/ci/tornado_1606942392901/work
tqdm @ file:///tmp/build/80754af9/tqdm_1615925068909/work
traitlets @ file:///home/ktietz/src/ci/traitlets_1611929699868/work
typed-ast @ file:///C:/ci/typed-ast_1610466535590/work
typeguard==2.13.3
typing-extensions @ file:///home/ktietz/src/ci_mi/typing_extensions_1612808209620/work
ujson @ file:///C:/ci/ujson_1611241570789/work
unicodecsv==0.14.1
uritemplate==4.1.1
urllib3 @ file:///tmp/build/80754af9/urllib3_1615837158687/work
watchdog @ file:///C:/ci/watchdog_1612471251191/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
weasyprint==56.1
webencodings==0.5.1
Werkzeug @ file:///home/ktietz/src/ci/werkzeug_1611932622770/work
wget==3.2
widgetsnbextension==3.5.1
win-inet-pton @ file:///C:/ci/win_inet_pton_1605306167264/work
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.12.1
xgboost==1.7.1
xlrd @ file:///tmp/build/80754af9/xlrd_1608072521494/work
XlsxWriter @ file:///tmp/build/80754af9/xlsxwriter_1617224712951/work
xlwings==0.23.0
xlwt==1.3.0
xmltodict==0.12.0
yapf @ file:///tmp/build/80754af9/yapf_1615749224965/work
yarl==1.7.2
yellowbrick==1.3
zict==2.0.0
zipp @ file:///tmp/build/80754af9/zipp_1615904174917/work
zope.event==4.5.0
zope.interface @ file:///C:/ci/zope.interface_1616357322857/work
zopfli==0.2.1
```

**Comment by lena-kashtelyan** [comment]
@JonAnderRuizColmenares  it seems to me that your question was answered, so I'm closing this issue. Please feel free to follow up on it, but if you do, please reopen the issue as we might not see your comment on a closed one.
