### ISSUE TITLE
ImportError: cannot import name 'optimize_acqf'

### ISSUE THREAD

**Issue by rgemulla** [facebook/Ax#159]
After updating to ax-platform 0.1.4 (with botorch 0.1.3, torch 1.2.0), importing AxClient raises an ImportError. In particular,

```python
from ax.service.ax_client import AxClient
```
gives error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/python3.6/site-packages/ax/__init__.py", line 5, in <module>
    from ax.modelbridge import Models
  File "[...]/python3.6/site-packages/ax/modelbridge/__init__.py", line 6, in <module>
    from ax.modelbridge.factory import (
  File "[...]/python3.6/site-packages/ax/modelbridge/factory.py", line 13, in <module>
    from ax.modelbridge.discrete import DiscreteModelBridge
  File "[...]/python3.6/site-packages/ax/modelbridge/discrete.py", line 18, in <module>
    from ax.models.discrete_base import DiscreteModel
  File "[...]/python3.6/site-packages/ax/models/__init__.py", line 5, in <module>
    from ax.models.torch.botorch import BotorchModel
  File "[...]/python3.6/site-packages/ax/models/torch/botorch.py", line 10, in <module>
    from ax.models.torch.botorch_defaults import (
  File "[...]/python3.6/site-packages/ax/models/torch/botorch_defaults.py", line 21, in <module>
    from botorch.optim.optimize import optimize_acqf
ImportError: cannot import name 'optimize_acqf'
```

**Comment by reachnatp** [comment]
I still ran into this issue while adapting tutorials/closed_loop_botorch_only.ipynb, I follows the mitigation steps at https://github.com/facebook/Ax#latest-version but still no avail. Should I just try logging an issue against botorch
