### ISSUE TITLE
`qKnowledgeGradient` with BOTORCH_MODULAR fails in benchmarks

### ISSUE THREAD

**Issue by esantorella** [facebook/Ax#1594]
Since roughly 4/21, using the latest versions of BoTorch and Ax, the following code has triggered an error:

```python

from ax.benchmark.benchmark import benchmark_full_run
from ax.benchmark.methods.modular_botorch import get_sobol_botorch_modular_acquisition
from ax.benchmark.problems.registry import get_problem
from botorch.acquisition.knowledge_gradient import qKnowledgeGradient

problem = get_problem(problem_name="ackley4")
method = get_sobol_botorch_modular_acquisition(acquisition_cls=qKnowledgeGradient)

benchmark_full_run(problems=[problem], methods=[method], seeds=[0])
```

It gives the following error:
```UnsupportedError: `batch_initial_conditions` is not supported for sequential optimization. Either avoid specifying `batch_initial_conditions` to use the custom initializer or use the `ic_generator` kwarg to generate initial conditions for the case of nonlinear inequality constraints.```

I'll fix this; posting in case anyone immediately knows what's up.

Here's the following traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/santorella/repos/ax/ax/benchmark/benchmark.py", line 129, in benchmark_full_run
    return [test_env(problem=p, method=m) for p, m in product(problems, methods)]
  File "/Users/santorella/repos/ax/ax/benchmark/benchmark.py", line 129, in <listcomp>
    return [test_env(problem=p, method=m) for p, m in product(problems, methods)]
  File "/Users/santorella/repos/ax/ax/benchmark/benchmark.py", line 118, in benchmark_test
    results=[base_case(seed=seed) for seed in seeds]
  File "/Users/santorella/repos/ax/ax/benchmark/benchmark.py", line 118, in <listcomp>
    results=[base_case(seed=seed) for seed in seeds]
  File "/Users/santorella/repos/ax/ax/benchmark/benchmark.py", line 69, in benchmark_replication
    scheduler.run_n_trials(max_trials=problem.num_trials)
  File "/Users/santorella/repos/ax/ax/service/scheduler.py", line 949, in run_n_trials
    for _ in self.run_trials_and_yield_results(
  File "/Users/santorella/repos/ax/ax/service/scheduler.py", line 865, in run_trials_and_yield_results
    while n_remaining_to_run > 0 and self.run(
  File "/Users/santorella/repos/ax/ax/service/scheduler.py", line 1044, in run
    existing_trials, new_trials = self._prepare_trials(
  File "/Users/santorella/repos/ax/ax/service/scheduler.py", line 1359, in _prepare_trials
    self._get_next_trials(num_trials=n_new, n=(self.options.batch_size or 1))
  File "/Users/santorella/repos/ax/ax/service/scheduler.py", line 1380, in _get_next_trials
    generator_runs = self._gen_new_trials_from_generation_strategy(
  File "/Users/santorella/repos/ax/ax/service/scheduler.py", line 1441, in _gen_new_trials_from_generation_strategy
    return self.generation_strategy._gen_multiple(
  File "/Users/santorella/repos/ax/ax/modelbridge/generation_strategy.py", line 479, in _gen_multiple
    generator_run = self._curr.gen(
  File "/Users/santorella/repos/ax/ax/modelbridge/generation_node.py", line 400, in gen
    gr = super().gen(
  File "/Users/santorella/repos/ax/ax/modelbridge/generation_node.py", line 193, in gen
    generator_run = model_spec.gen(
  File "/Users/santorella/repos/ax/ax/modelbridge/model_spec.py", line 225, in gen
    return fitted_model.gen(**model_gen_kwargs)
  File "/Users/santorella/repos/ax/ax/modelbridge/base.py", line 767, in gen
    gen_results = self._gen(
  File "/Users/santorella/repos/ax/ax/modelbridge/torch.py", line 561, in _gen
    gen_results = not_none(self.model).gen(
  File "/Users/santorella/repos/ax/ax/models/torch/botorch_modular/model.py", line 457, in gen
    candidates, expected_acquisition_value = acqf.optimize(
  File "/Users/santorella/repos/ax/ax/models/torch/botorch_modular/acquisition.py", line 431, in optimize
    return optimize_acqf(
  File "/Users/santorella/opt/anaconda3/envs/axdev/lib/python3.10/site-packages/botorch/optim/optimize.py", line 519, in optimize_acqf
    opt_acqf_inputs = OptimizeAcqfInputs(
  File "<string>", line 23, in __init__
  File "/Users/santorella/opt/anaconda3/envs/axdev/lib/python3.10/site-packages/botorch/optim/optimize.py", line 120, in __post_init__
    raise UnsupportedError(
botorch.exceptions.errors.UnsupportedError: `batch_initial_conditions` is not supported for sequential optimization. Either avoid specifying `batch_initial_conditions` to use the custom initializer or use the `ic_generator` kwarg to generate initial conditions for the case of nonlinear inequality constraints.
```

**Comment by esantorella** [comment]
Closed by #1598
