### ISSUE TITLE
evaluate_acquisition_function with qKnowledgeGradient get TypeError: evaluate() missing 1 required positional argument: 'bounds'

### ISSUE THREAD

**Issue by smao-astro** [facebook/Ax#1719]
Dear developers and contributors,

I am new to Ax and I am trying to get the profile of the qKnowledgeGradient acquisition function. The code is

```python
#!/usr/bin/env python
# coding: utf-8

import ax.modelbridge.generation_strategy
import ax.modelbridge.registry
import ax.models.torch.botorch_modular.acquisition
import ax.models.torch.botorch_modular.surrogate
import ax.plot.slice

# ax
import ax.service.ax_client

# botorch
import botorch.acquisition.knowledge_gradient

import numpy as np
import plotly.express as px

NUM_SOBOL = 5

# # objective function and parameter space


# 1d function
def f(x):
    return np.cos(2 * x) + x


x_range = (0, 1.5 * np.pi)
xs = np.linspace(*x_range, 100)
fs = f(xs)
# plot
fig = px.line(x=xs, y=fs)
fig.show()


def obj(parameters):
    x = parameters.get("x")
    return {"y": f(x)}


gs = ax.modelbridge.generation_strategy.GenerationStrategy(
    steps=[
        # 1. Initialization step (does not require pre-existing data and is well-suited for
        # initial sampling of the search space)
        ax.modelbridge.generation_strategy.GenerationStep(
            model=ax.modelbridge.registry.Models.SOBOL,
            num_trials=5,  # How many trials should be produced from this generation step
            min_trials_observed=3,  # How many trials need to be completed to move to next model
            max_parallelism=5,  # Max parallelism for this step
            model_kwargs={"seed": 999},  # Any kwargs you want passed into the model
            model_gen_kwargs={},  # Any kwargs you want passed to `modelbridge.gen`
        ),
        # 2. Bayesian optimization step (requires data obtained from previous phase and learns
        # from all data available at the time of each new candidate generation call)
        ax.modelbridge.generation_strategy.GenerationStep(
            model=ax.modelbridge.registry.Models.BOTORCH_MODULAR,
            num_trials=-1,  # No limitation on how many trials should be produced from this step
            max_parallelism=3,  # Parallelism limit for this step, often lower than for Sobol
            # More on parallelism vs. required samples in BayesOpt:
            # https://ax.dev/docs/bayesopt.html#tradeoff-between-parallelism-and-total-number-of-trials
            model_kwargs={
                "surrogate": ax.models.torch.botorch_modular.surrogate.Surrogate(
                    botorch.models.gp_regression.SingleTaskGP
                ),
                # "botorch_acqf_class": botorch.acquisition.monte_carlo.qExpectedImprovement,
                # "botorch_acqf_class": botorch.acquisition.monte_carlo.qNoisyExpectedImprovement,
                "botorch_acqf_class": botorch.acquisition.knowledge_gradient.qKnowledgeGradient,
            },
        ),
    ]
)

ax_client = ax.service.ax_client.AxClient(generation_strategy=gs)

ax_client.create_experiment(
    name="test_experiment",
    parameters=[
        {
            "name": "x",
            "type": "range",
            "bounds": list(x_range),
            "value_type": "float",
            "log_scale": False,
        }
    ],
    objective_name="y",
    minimize=True,
)


for i in range(10):
    parameters, trial_index = ax_client.get_next_trial()
    # Local evaluation here can be replaced with deployment to external system.
    ax_client.complete_trial(trial_index=trial_index, raw_data=obj(parameters))
    # input("Press Enter to continue...")
    if i > NUM_SOBOL:
        fig = ax.plot.slice.plot_slice_plotly(
            ax_client.generation_strategy.model, "x", "y"
        )
        fig.show()
        #
        acq_values = ax_client.generation_strategy.model.evaluate_acquisition_function(
            observation_features=[
                ax.core.observation.ObservationFeatures({"x": x}) for x in xs
            ],
            search_space=ax_client.experiment.search_space,
        )
        # plot
        fig_acq = px.line(x=xs, y=acq_values)
        fig_acq.show()
```
The code above works for `botorch.acquisition.monte_carlo.qExpectedImprovement` or `botorch.acquisition.monte_carlo.qNoisyExpectedImprovement`. However, when I run it with `qKnowledgeGradient`, I got the error below
```
/Users/kyika/project/learn_ax/.venv/bin/python3 /Users/kyika/project/learn_ax/visualize_1d_1_1_acquisition.py 
[INFO 07-16 22:16:39] ax.service.ax_client: Starting optimization with verbose logging. To disable logging, set the `verbose_logging` argument to `False`. Note that float values in the logs are rounded to 6 decimal points.
[INFO 07-16 22:16:39] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[RangeParameter(name='x', parameter_type=FLOAT, range=[0.0, 4.71238898038469])], parameter_constraints=[]).
[INFO 07-16 22:16:39] ax.service.ax_client: Generated new trial 0 with parameters {'x': 2.962819}.
[INFO 07-16 22:16:39] ax.service.ax_client: Completed trial 0 with data: {'y': (3.899578, None)}.
[INFO 07-16 22:16:39] ax.service.ax_client: Generated new trial 1 with parameters {'x': 1.309568}.
[INFO 07-16 22:16:39] ax.service.ax_client: Completed trial 1 with data: {'y': (0.442972, None)}.
[INFO 07-16 22:16:39] ax.service.ax_client: Generated new trial 2 with parameters {'x': 0.462538}.
[INFO 07-16 22:16:39] ax.service.ax_client: Completed trial 2 with data: {'y': (1.064312, None)}.
[INFO 07-16 22:16:39] ax.service.ax_client: Generated new trial 3 with parameters {'x': 4.692873}.
[INFO 07-16 22:16:39] ax.service.ax_client: Completed trial 3 with data: {'y': (3.693634, None)}.
[INFO 07-16 22:16:39] ax.service.ax_client: Generated new trial 4 with parameters {'x': 4.023798}.
[INFO 07-16 22:16:39] ax.service.ax_client: Completed trial 4 with data: {'y': (3.831391, None)}.
[INFO 07-16 22:16:41] ax.service.ax_client: Generated new trial 5 with parameters {'x': 1.814377}.
[INFO 07-16 22:16:41] ax.service.ax_client: Completed trial 5 with data: {'y': (0.930711, None)}.
[INFO 07-16 22:16:42] ax.service.ax_client: Generated new trial 6 with parameters {'x': 2.998902}.
[INFO 07-16 22:16:42] ax.service.ax_client: Completed trial 6 with data: {'y': (3.958456, None)}.
Traceback (most recent call last):
  File "/Users/kyika/project/learn_ax/visualize_1d_1_1_acquisition.py", line 103, in <module>
    acq_values = ax_client.generation_strategy.model.evaluate_acquisition_function(
  File "/Users/kyika/project/learn_ax/.venv/lib/python3.9/site-packages/ax/modelbridge/torch.py", line 446, in evaluate_acquisition_function
    return self._evaluate_acquisition_function(
  File "/Users/kyika/project/learn_ax/.venv/lib/python3.9/site-packages/ax/modelbridge/torch.py", line 480, in _evaluate_acquisition_function
    evals = not_none(self.model).evaluate_acquisition_function(
  File "/Users/kyika/project/learn_ax/.venv/lib/python3.9/site-packages/ax/models/torch/botorch_modular/model.py", line 528, in evaluate_acquisition_function
    return acqf.evaluate(X=X)
  File "/Users/kyika/project/learn_ax/.venv/lib/python3.9/site-packages/ax/models/torch/botorch_modular/acquisition.py", line 544, in evaluate
    return self.acqf.evaluate(X=X)
  File "/Users/kyika/project/learn_ax/.venv/lib/python3.9/site-packages/botorch/utils/transforms.py", line 330, in decorated
    return method(cls, X, **kwargs)
  File "/Users/kyika/project/learn_ax/.venv/lib/python3.9/site-packages/botorch/utils/transforms.py", line 287, in decorated
    output = method(acqf, X, *args, **kwargs)
TypeError: evaluate() missing 1 required positional argument: 'bounds'

Process finished with exit code 1
```

I am eager to visualize the qKnowledgeGradient function. Could you please guide me on how to fix this error? I would greatly appreciate any assistance.

**Comment by lena-kashtelyan** [comment]
@smao-astro, may I ask for a bit more context about what you are doing and why you choosing KG specifically? Just for my knowledge and so I can help in the best way.

**Comment by lena-kashtelyan** [comment]
Merged to a larger KG issue.

**Comment by esantorella** [comment]
I'm not sure what changed, but this seems to be working now. (I confirmed that it was not working previously.) Using the new Ax API:

```python
import ax.adapter.registry
import ax.generators.torch.botorch_modular.acquisition
import ax.plot.slice

import ax.service.ax_client

import numpy as np
import plotly.express as px
from ax.adapter.registry import Generators
from ax.api.client import Client
from ax.api.configs import RangeParameterConfig
from ax.generation_strategy.center_generation_node import CenterGenerationNode
from ax.generation_strategy.generation_node import GenerationNode
from ax.generation_strategy.generation_strategy import GenerationStrategy
from ax.generation_strategy.generator_spec import GeneratorSpec
from ax.generation_strategy.transition_criterion import MinTrials

from botorch.acquisition.knowledge_gradient import qKnowledgeGradient

# Set up GenerationStrategy
generator_spec = GeneratorSpec(
    generator_enum=Generators.BOTORCH_MODULAR,
    model_kwargs={"botorch_acqf_class": qKnowledgeGradient},
)

botorch_node = GenerationNode(node_name="BoTorch", generator_specs=[generator_spec])
sobol_node = GenerationNode(
    node_name="Sobol",
    generator_specs=[GeneratorSpec(generator_enum=Generators.SOBOL)],
    transition_criteria=[
        # Transition to BoTorch node once there are 5 trials on the experiment.
        MinTrials(
            threshold=5,
            transition_to=botorch_node.node_name,
            use_all_trials_in_exp=True,
        )
    ],
)
# Center node is a customized node that uses a simplified logic and has a
# built-in transition criteria that transitions after generating once.
center_node = CenterGenerationNode(next_node_name=sobol_node.node_name)
generation_strategy = GenerationStrategy(
    name="Center+Sobol+BoTorch", nodes=[center_node, sobol_node, botorch_node]
)

# Set up Client
client = Client()
range_parameters = [
    RangeParameterConfig(name="x", parameter_type="float", bounds=(0, 1))
]
client.configure_experiment(parameters=range_parameters)
metric_name = "test_metric"
objective = f"-{metric_name}"
client.configure_optimization(objective=objective)


def test_function(x):
    # A made-up function.
    return x**2.0


client.set_generation_strategy(generation_strategy=generation_strategy)

for _ in range(10):
    trials = client.get_next_trials(max_trials=1)
    for index, parameters in trials.items():
        result = test_function(**parameters)
        client.complete_trial(trial_index=index, raw_data={metric_name: result})


# plot
xs = np.linspace(0, 1, 100)

fig = ax.plot.slice.plot_slice_plotly(generation_strategy.adapter, "x", metric_name)
fig.show()
acq_values = generation_strategy.adapter.evaluate_acquisition_function(
    observation_features=[
        ax.core.observation.ObservationFeatures({"x": x}) for x in xs
    ],
    search_space=client.experiment.search_space,
)

fig_acq = px.line(x=xs, y=acq_values)
fig_acq.show()
```
