### ISSUE TITLE
TypeError: must be real number, not NoneType

### ISSUE THREAD

**Issue by ga92xug** [facebook/Ax#1779]
I am doing a NAS with AX. I am running into the following error when I am running the optimization. The reason for these are the stride constraint and the out_channel constraint. I have thought about if there is a way around it but it seems like this is the only way to do that. If you need more information on this issue please let me know 

```
Running trial 0
Running trial 1
Sample: 100%|████████████████████████████| 768/768 [02:12,  5.78it/s, step size=3.52e-01, acc. prob=0.904]

Sample: 100%|████████████████████████████| 768/768 [02:16,  5.62it/s, step size=3.80e-01, acc. prob=0.886]

Sample: 100%|████████████████████████████| 768/768 [02:16,  5.64it/s, step size=3.88e-01, acc. prob=0.870]

/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/botorch/optim/initializers.py:403: BadInitialCandidatesWarning: Unable to find non-zero acquisition function values - initial conditions are being selected randomly.
  warnings.warn(
Traceback (most recent call last):
  File "/home/frischs/dev1/scaling-laws-ecnn/NAS/minimal_example.py", line 278, in <module>
    main()
  File "/home/frischs/dev1/scaling-laws-ecnn/NAS/minimal_example.py", line 266, in main
    trial = ax_client.get_next_trial()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/utils/common/executils.py", line 161, in actual_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/service/ax_client.py", line 545, in get_next_trial
    generator_run=self._gen_new_generator_run(), ttl_seconds=ttl_seconds
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/service/ax_client.py", line 1734, in _gen_new_generator_run
    return not_none(self.generation_strategy).gen(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/modelbridge/generation_strategy.py", line 334, in gen
    return self._gen_multiple(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/modelbridge/generation_strategy.py", line 479, in _gen_multiple
    generator_run = self._curr.gen(
                    ^^^^^^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/modelbridge/generation_node.py", line 408, in gen
    gr = super().gen(
         ^^^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/modelbridge/generation_node.py", line 193, in gen
    generator_run = model_spec.gen(
                    ^^^^^^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/modelbridge/model_spec.py", line 225, in gen
    return fitted_model.gen(**model_gen_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/modelbridge/base.py", line 805, in gen
    gen_results = self._gen(
                  ^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/modelbridge/torch.py", line 628, in _gen
    ] = self._untransform_objective_thresholds(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/modelbridge/torch.py", line 851, in _untransform_objective_thresholds
    fixed_features_obs = t.untransform_observation_features(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/modelbridge/transforms/int_to_float.py", line 134, in untransform_observation_features
    rounded_parameters = randomized_round_parameters(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/modelbridge/transforms/rounding.py", line 73, in randomized_round_parameters
    rounded_parameters[p_name] = randomized_round(param)
                                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frischs/anaconda3/envs/ax/lib/python3.11/site-packages/ax/modelbridge/transforms/rounding.py", line 20, in randomized_round
    z = math.floor(x)
        ^^^^^^^^^^^^^
TypeError: must be real number, not NoneType
```

Minimum working example:

```
import torch
import numpy as np
from ax.service.ax_client import AxClient, ObjectiveProperties
from ax.modelbridge.generation_strategy import GenerationStep, GenerationStrategy
from ax.modelbridge.registry import Models

import logging
from ax.utils.common.logger import ROOT_STREAM_HANDLER
ROOT_STREAM_HANDLER.setLevel(logging.ERROR)


class Search_Space:
    def __init__(self, num_middle_blocks=3):
        self.num_middle_blocks = num_middle_blocks
        self.choice_2_range_params = {"group": [1, 2, 4, 8, 16]}
        self.parameters = []

        # block search space
        # block_id = 0 is the stem block
        # block_id = blocks+1 is the head block
        for block_id in range(0, self.num_middle_blocks+2):
            self.parameters.extend(self.per_block_search_space(block_id))

        self.parameter_constraints = self.get_constraints()

    def get_constraints(self):       
        parameter_constraints = []
        strides_constraint = ""
        out_channels_constraint = ""
        total_number_blocks = self.num_middle_blocks+2
        out_channels_prefactor = np.linspace(1, 0.1, total_number_blocks)

        for block_id in range(0, total_number_blocks):
            if block_id == 0:
                strides_constraint += f"{block_id}_stride"
                out_channels_constraint += f"{out_channels_prefactor[block_id]}*{block_id}_out_channels"
                continue

            # the group must never increase
            group_decrease_constraint = f"{block_id-1}_group >= {block_id}_group"
            parameter_constraints.append(group_decrease_constraint)
            
            # the reflection must never increase
            reflection_decrease_constraint = f"{block_id-1}_reflection >= {block_id}_reflection"
            parameter_constraints.append(reflection_decrease_constraint)

            strides_constraint += f" + {block_id}_stride"
            out_channels_constraint += f" + {out_channels_prefactor[block_id]}*{block_id}_out_channels"

        # stride constraint
        stride_constraint = f"{strides_constraint} >= {6}"
        parameter_constraints.append(stride_constraint)
            
        # out_channels constraint
        out_channels_constraint += f" <= {6}"
        parameter_constraints.append(out_channels_constraint)

        return parameter_constraints

    def per_block_search_space(self, block_id):
        block_search_space = []

        if block_id == 0:
            block_search_space.extend([
                self.get_reflection(block_id),
                self.get_group(block_id),
                self.get_out_channels(block_id),
                self.get_kernel_size(block_id),
                self.get_stride(block_id),
            ])
                                      
            return block_search_space
        
        elif block_id == self.num_middle_blocks+1:
            block_search_space.extend([
                self.get_reflection(block_id),
                self.get_group(block_id),
                self.get_out_channels(block_id),
                self.get_kernel_size(block_id),
                self.get_stride(block_id),
            ])
            return block_search_space
        
        else:
            block_search_space.extend([
                self.get_reflection(block_id),
                self.get_group(block_id),
                self.get_num_layers(block_id),
                self.get_conv_op(block_id),
                self.get_kernel_size(block_id),
                self.get_se_ratio(block_id),
                self.get_out_channels(block_id),
                self.get_skip_op(block_id),
                self.get_stride(block_id),
            ])
            return block_search_space


    def get_reflection(self, block_id):
        return {
            "name": f"{block_id}_reflection",
            "type": "range",
            "bounds": [-1, 0],
            "value_type": "int",
        }

    def get_group(self, block_id):
        return {
            "name": f"{block_id}_group",
            "type": "range",
            "bounds": [0, len(self.choice_2_range_params["group"]) - 1],
            "value_type": "int",
        }

    def get_num_layers(self, block_id):
        return {
            "name": f"{block_id}_num_layers",
            "type": "range",
            "bounds": [1,2],
            "value_type": "int",
        }

    def get_conv_op(self, block_id):
        return {
            "name": f"{block_id}_conv_op",
            "type": "choice",
            "values": ["conv", "dconv", "mbconv"],
            "value_type": "str",
            "is_ordered": True,
        }

    def get_kernel_size(self, block_id):
        return {
            "name": f"{block_id}_kernel_size",
            "type": "choice",
            "values": [3,5],
            "value_type": "int",
            "is_ordered": True,
        }

    def get_se_ratio(self, block_id):
        return {
            "name": f"{block_id}_se_ratio",
            "type": "choice",
            "values": [0.25, 0.5, 0.75],
            "value_type": "float",
            "is_ordered": True,
        }

    def get_skip_op(self, block_id):
        return {
            "name": f"{block_id}_skip_op",
            "type": "choice",
            "values": ["no", "identity", "conv"],
            "value_type": "str",
            "is_ordered": True,
        }

    def get_out_channels(self, block_id):
        return {
            "name": f"{block_id}_out_channels",
            "type": "range",
            "bounds": [1.,4.],
            "value_type": "float",
            "is_ordered": True,
        }
        
    def get_stride(self, block_id):
        return {
            "name": f"{block_id}_stride",
            "type": "range",
            "bounds": [1, 2],
            "value_type": "int",
            "is_ordered": True,
        }
        

    def get_expand_ratio(self):
        return {
            "name": f"-1_expand_ratio",
            "type": "choice",
            "values": [2,4,6],
            "value_type": "int",
            "is_ordered": True,
        }
    
    def get_dropout_rate(self):
        return {
            "name": f"-1_dropout_rate",
            "type": "fixed",
            "value": 0.0,
            "value_type": "float",
        }
        
    def get_search_space(self):
        return self.search_space
    
    def get_parameters(self):
        return self.parameters
    
    def get_parameter_constraints(self):
        return self.parameter_constraints


def generate_random_data():
    # generate random data
    data = {
            "valid_acc": np.random.uniform(0.7, 0.9),
            "gflops": np.random.uniform(100, 200),
            "model_building_time": np.random.uniform(10, 100),
        }
    return data


def main():
        device = torch.device('cuda' if torch.cuda.is_available() \
                                   else "cpu")
        generation_strategy=GenerationStrategy(
            name="SAASBO",
            steps=[
                GenerationStep(
                    model=Models.SOBOL,
                    num_trials=5
                ),
                GenerationStep(
                    model=Models.FULLYBAYESIANMOO,
                    num_trials=25,
                    model_kwargs={
                        "torch_device": device,
                        "num_samples": 256,
                        "warmup_steps": 512,
                    },
                    max_parallelism=1,
                )
            ],
        )

        ax_client = AxClient(
                generation_strategy=generation_strategy,
            )

        eq_search_space = Search_Space()
        parameter = eq_search_space.get_parameters()
        parameter_constraints = eq_search_space.get_parameter_constraints()

        ax_client.create_experiment(
            parameters=parameter,
            support_intermediate_data=True,
            objectives={
                # `threshold` arguments are optional
                "valid_acc": ObjectiveProperties(
                    minimize=False, 
                    threshold=0.8
                ), 
                "gflops": ObjectiveProperties(
                    minimize=True, 
                    threshold=150
                )
            },
            parameter_constraints=parameter_constraints,
            tracking_metric_names=["model_building_time"],
        )

        for i in range(30):
            print(f"Running trial {i}")
            trial = ax_client.get_next_trial()
            _, trial_index = trial

            data = generate_random_data()

            ax_client.complete_trial(
                    trial_index=trial_index, 
                    raw_data=data,
                )
            
        
if __name__ == "__main__":
    main()
```

**Comment by Balandat** [comment]
Thanks for the minimal repro, I can indeed repro this locally. Looks like fundamentally this is caused by one of the objective thresholds being `NaN`, which is then being (attempted to be) untransformed. This occurs with the tracking metric `model_building_time` in this case. I think the fact that they can be `NaN` is intended, but somehow this doesn't play well with the untransform. @sdaulton I recall you worked on this logic, could you please take a look? 

```
> /Users/balandat/Code/Ax/ax/modelbridge/transforms/rounding.py(20)randomized_round()
     18 def randomized_round(x: float) -> int:
     19     """Randomized round of x"""
---> 20     z = math.floor(x)
     21     return int(z + float(random.random() <= (x - z)))
     22 

ipdb> !x
ipdb> !x is None
True
ipdb> up
> /Users/balandat/Code/Ax/ax/modelbridge/transforms/rounding.py(73)randomized_round_parameters()
     70         # pyre: param is declared to have type `float` but is used as
     71         # pyre-fixme[9]: type `Optional[typing.Union[bool, float, str]]`.
     72         param: float = parameters.get(p_name)
---> 73         rounded_parameters[p_name] = randomized_round(param)
     74     return rounded_parameters

ipdb> !param
ipdb> up
> /Users/balandat/Code/Ax/ax/modelbridge/transforms/int_to_float.py(134)untransform_observation_features()
    132             else:
    133                 round_attempts = 0
--> 134                 rounded_parameters = randomized_round_parameters(
    135                     obsf.parameters, self.transform_parameters
    136                 )

ipdb> !obsf
ObservationFeatures(parameters={})
ipdb> up
> /Users/balandat/Code/Ax/ax/modelbridge/torch.py(851)_untransform_objective_thresholds()
    849                 # Cast transform requires a valid hierarchical parameterization.
    850                 # `fixed_features_obs` is incomplete, so it leads to an error.
--> 851                 fixed_features_obs = t.untransform_observation_features(
    852                     [fixed_features_obs]
    853                 )[0]

ipdb> !fixed_features_obs
ObservationFeatures(parameters={})
ipdb> up
> /Users/balandat/Code/Ax/ax/modelbridge/torch.py(628)_gen()
    626             gen_metadata[
    627                 "objective_thresholds"
--> 628             ] = self._untransform_objective_thresholds(
    629                 objective_thresholds=gen_metadata["objective_thresholds"],
    630                 objective_weights=torch_opt_config.objective_weights,

ipdb> !gen_metadata
{'expected_acquisition_value': 0.5780615286756967, 'objective_thresholds': tensor([0.1596,    nan, 0.5905], dtype=torch.float64), 'objective_weights': tensor([-1.,  0.,  1.], dtype=torch.float64)}
```

**Comment by ga92xug** [comment]
@Balandat thanks for the reply. Can I somehow set the objective threshold of the model building time during the experiment creation, so I can move forward with the experiment? Or does this make no sense. 

Another matter are the warnings e.g. [WARNING 08-17 13:11:38] ax.modelbridge.transforms.int_to_float: Unable to round. I assume this is because I chose some parameter constraints to span multiple float params e.g. out_channels_constraint. Does this have any impact on the performance? Can I remove this problem somehow in this setting or do I just supress the warning with the logging as I have done in the minimal repro?

**Comment by sdaulton** [comment]
Yeah you can set the objective threshold for `model_building_time` to some real number for now to unblock. That won't affect performance

**Comment by ga92xug** [comment]
Sorry for this small question but I could not find an answer in the documentation and none of the issues show how to do this with the service API. How do I set an objective threshold for a tracking metrics? This is what I tried:
```
tracking_metric_names=["model_building_time"],
metric_definitions={"model_building_time": ObjectiveProperties(
                    minimize=True, 
                    threshold=150
                )},
                
  File "/home/stefan/git/Ax/ax/service/utils/instantiation.py", line 126, in _make_metric
    return metric_class(
           ^^^^^^^^^^^^^
TypeError: ax.core.metric.Metric() argument after ** must be a mapping, not ObjectiveProperties

**Comment by sdaulton** [comment]
Hmm, yeah that wouldn't be possible without changing the underlying code. You could omit it for the time being and track it outside of Ax. I am looking into the issue here now

**Comment by ga92xug** [comment]
Ah I see. The thing is I need the model_building_time for "early stopping" some trials that suggested very large architectures. Ax needs a reason for the early stopping otherwise it suggests that trial again. Currently, I do that like this:
`outcome_constraints=[f"model_building_time <= {self.cfg.objective.max_building_time - 1}"],`
So for my use case, an outcome_constraint would be pretty much the same as a threshold, if I understand this correctly.

**Comment by sdaulton** [comment]
Alrighty. Fixed it. PR coming soon

**Comment by sdaulton** [comment]
This aught to fix it: https://github.com/facebook/Ax/pull/1789

I ran your code with errors

**Comment by ga92xug** [comment]
Thanks, that fixes the problem.
