### ISSUE TITLE
Import AxClient fails if SQLAlchemy not installed

### ISSUE THREAD

**Issue by casassg** [facebook/Ax#191]
Importing `AxClient` fails if environment doesn't have SQLAlchemy installed. Not sure if this the intended behaviour as it seems that SQLAlchemy is an optional dependency.

Easy to fix for me, as I was planning to use SQLAlchemy to store state either way, but just wanted to make sure this was properly notified 😄 

Python version: `3.7.4`
Ax version: `0.1.6`
Logs:

```
>>> from ax.service.ax_client import AxClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/temp/.local/share/virtualenvs/local_ipynb-rHeTa3va/lib/python3.7/site-packages/ax/service/ax_client.py", line 36, in <module>
    from ax.service.utils.storage import (
  File "/Users/temp/.local/share/virtualenvs/local_ipynb-rHeTa3va/lib/python3.7/site-packages/ax/service/utils/storage.py", line 8, in <module>
    from ax.storage.sqa_store.db import init_engine_and_session_factory
  File "/Users/temp/.local/share/virtualenvs/local_ipynb-rHeTa3va/lib/python3.7/site-packages/ax/storage/sqa_store/__init__.py", line 6, in <module>
    from ax.storage.sqa_store import validation
  File "/Users/temp/.local/share/virtualenvs/local_ipynb-rHeTa3va/lib/python3.7/site-packages/ax/storage/sqa_store/validation.py", line 6, in <module>
    from ax.storage.sqa_store.db import SQABase
  File "/Users/temp/.local/share/virtualenvs/local_ipynb-rHeTa3va/lib/python3.7/site-packages/ax/storage/sqa_store/db.py", line 14, in <module>
    from sqlalchemy import create_engine, inspect
ModuleNotFoundError: No module named 'sqlalchemy'
```

**Comment by lena-kashtelyan** [comment]
This is a bug; thank you so much for bringing it to our attention!

**Comment by casassg** [comment]
Is there any approximate timeframe for this to be released?

**Comment by lena-kashtelyan** [comment]
@casassg, this issue should be fixed on `master` (check https://github.com/facebook/Ax#latest-version for installation instructions) –– would you like to try it? Please let me know if you run into any more issues!

**Comment by casassg** [comment]
Works nicely now! Is there any public doc on release schedule though? I may wait until the next version is released to `Pypi` and just push the version number then.

**Comment by lena-kashtelyan** [comment]
@casassg, we don't actually have a release schedule per se; I'll see if we can cut a release by next week though : )

**Comment by casassg** [comment]
Is there any update on the release? SQLAlchemy is currently blocking us due to a dependency issue we have. 

Per https://github.com/facebook/Ax/pull/216#issuecomment-561285577 I guess the travis fix is going first?

**Comment by lena-kashtelyan** [comment]
Commented on #216; will aim to cut a new version by Friday (maybe sooner)! Apologies for the delays, it's been a busy time and we wanted to include a couple significant bug fixes in the new cut.

**Comment by lena-kashtelyan** [comment]
The import bug fix is now part of the latest stable version, 0.1.8!
