### ISSUE TITLE
Trouble using ChoiceParameter

### ISSUE THREAD

**Issue by aleczhanshi** [facebook/Ax#270]
Hi there,

When I'm having a ChoiceParameter in the optimize function, I got this error 

```python
Traceback (most recent call last):
  File "bo_ax.py", line 103, in <module>
    parameter_constraints=["x0 + x2 >= 5.0", "x1 + x3 >= 5.0", "x0 + x2 <= 5.0", "x1 + x3 <= 5.0", "x2 + x3 <= 4.0"],
  File "/u/zshi17/.local/lib/python3.6/site-packages/ax/service/managed_loop.py", line 222, in optimize
    generation_strategy=generation_strategy,
  File "/u/zshi17/.local/lib/python3.6/site-packages/ax/service/managed_loop.py", line 85, in with_evaluation_function
    exp_parameters = [parameter_from_json(p) for p in parameters]
  File "/u/zshi17/.local/lib/python3.6/site-packages/ax/service/managed_loop.py", line 85, in <listcomp>
    exp_parameters = [parameter_from_json(p) for p in parameters]
  File "/u/zshi17/.local/lib/python3.6/site-packages/ax/service/utils/instantiation.py", line 138, in parameter_from_json
    name = representation["name"]
TypeError: 'ChoiceParameter' object is not subscriptable
```
and here's my code

```python
best_parameters, values, experiment, model = optimize(
    parameters=[
        {
            "name": "x0",
            "type": "range",
            "bounds": [0, 5],
            "value_type": "int",
        },
        {  
            "name": "x1",
            "type": "range",
            "bounds": [0, 5],
            "value_type": "int",
        },
        {  
            "name": "x2",
            "type": "range",
            "bounds": [0, 5],
            "value_type": "int",
        },
        {  
            "name": "x3",
            "type": "range",
            "bounds": [0, 5],
            "value_type": "int",
        },        
        ChoiceParameter(
            name="permutation",
            parameter_type=ParameterType.STRING,
            values=["".join(x) for x in list(itertools.permutations(['K', 'P', 'C', 'R']))],
        ),
    ],
    evaluation_function=mapping,
    minimize=True,
    total_trials=100,
    parameter_constraints=["x0 + x2 >= 5.0", "x1 + x3 >= 5.0", "x0 + x2 <= 5.0", "x1 + x3 <= 5.0", "x2 + x3 <= 4.0"],
)
```
The error holds even when other parameters and constraints are taken away. Did I miss anything?

**Comment by ldworkin** [comment]
Hi @aleczhanshi ! So you're mixing up the types here. `parameters` should be a list of dictionaries only -- you're passing in some dictionaries, along with a `ChoiceParameter` object. Replace the `ChoiceParameter` object with the corresponding dictionary, i.e. `{"name": "permutation", "type": "choice", "values": ...}` and you should be all set. Let me know if that works!

**Comment by aleczhanshi** [comment]
Thanks it helped!
