### ISSUE TITLE
Consistent (but random) InputDataError: Input data contains NaN values - Passing new trials to GP+EI 

### ISSUE THREAD

**Issue by WolVecz** [facebook/Ax#337]
Hello, 

I have been playing with utilizing AX with the GP+EI Optimization and with Sklearn clustering functions. As part of this play, I have been utilizing AX to look at a large number of different clustering algorithms iteratively. I have consistently had the same error over and over (shown below), however it has also been highly random. While it occurs in ~19/20 runs that I have performed, it could occur during any iteration of the code once attempting to utilize the gpei model, though most commonly during the first gpei iteration of a new clustering algorithm).  I have been unable to isolate what exactly it causing it, but it seems as though that the experiment is not passing a new_trial call back into the function. The error rate seems to increase (happens earlier in the process) if the metric being utilized is more complex ( I have a much more complex metric than the one in the play code below and it has never once been able to make it past the third clustering algorithm iteration). I have also attempted this same code with batch trials and non-SimpleExperiment methods, but have consistently run into the same error. 

Here is the error  that I am constantly getting:
```
Traceback (most recent call last):

  File "<ipython-input-3-6c25aa8f0b12>", line 241, in <module>
    vals = cluster.cluster(blobs)

  File "<ipython-input-3-6c25aa8f0b12>", line 229, in cluster
    gpei = Models.BOTORCH(experiment=exp, data=exp.eval())

  File "C:\Users\se01040434\Anaconda3\lib\site-packages\ax\modelbridge\registry.py", line 271, in __call__
    **bridge_kwargs,

  File "C:\Users\se01040434\Anaconda3\lib\site-packages\ax\modelbridge\torch.py", line 77, in __init__
    fit_out_of_design=fit_out_of_design,

  File "C:\Users\se01040434\Anaconda3\lib\site-packages\ax\modelbridge\base.py", line 162, in __init__
    observation_data=obs_data,

  File "C:\Users\se01040434\Anaconda3\lib\site-packages\ax\modelbridge\torch.py", line 91, in _fit
    observation_data=observation_data,

  File "C:\Users\se01040434\Anaconda3\lib\site-packages\ax\modelbridge\array.py", line 84, in _fit
    candidate_metadata=candidate_metadata,

  File "C:\Users\se01040434\Anaconda3\lib\site-packages\ax\modelbridge\torch.py", line 122, in _model_fit
    candidate_metadata=candidate_metadata,

  File "C:\Users\se01040434\Anaconda3\lib\site-packages\ax\models\torch\botorch.py", line 294, in fit
    **self._kwargs,

  File "C:\Users\se01040434\Anaconda3\lib\site-packages\ax\models\torch\botorch_defaults.py", line 98, in get_and_fit_model
    **kwargs,

  File "C:\Users\se01040434\Anaconda3\lib\site-packages\ax\models\torch\botorch_defaults.py", line 481, in _get_model
    gp = SingleTaskGP(train_X=X, train_Y=Y, **kwargs)

  File "C:\Users\se01040434\Anaconda3\lib\site-packages\botorch\models\gp_regression.py", line 91, in __init__
    validate_input_scaling(train_X=train_X, train_Y=train_Y)

  File "C:\Users\se01040434\Anaconda3\lib\site-packages\botorch\models\utils.py", line 220, in validate_input_scaling
    check_no_nans(train_Y)

  File "C:\Users\se01040434\Anaconda3\lib\site-packages\botorch\models\utils.py", line 129, in check_no_nans
    raise InputDataError("Input data contains NaN values.")

InputDataError: Input data contains NaN values.
```

Here is the play code:
```
`import time
import numpy as np
import pandas as pd
from tqdm import tqdm

from ax import (
    ParameterType,
    RangeParameter,
    ChoiceParameter,
    SearchSpace,
    SimpleExperiment, 
    modelbridge,
    Models,
    Runner
)

from sklearn.cluster import (KMeans, 
                             MeanShift,
                             AffinityPropagation,
                             SpectralClustering,
                             AgglomerativeClustering,
                             DBSCAN,
                             OPTICS
)

from scipy.spatial.distance import pdist
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score
        

class ClusterEnesemble():
    
    def sklearnEvalFunction(self, parameterization, weight = None):

        alg    = self.model[1]
        
        params = dict()
        for value in self.model[2].keys():
            params[value] = parameterization[value]
        
        model = alg.set_params(**params)
        labels = model.fit_predict(self.df)
        
        if len(list(set(labels))) < 2:
            return (float("inf"), 0.0)
        else: 
            score = silhouette_score(self.df, labels)
            return (score, 0.0)
    
    @staticmethod
    def generateSearchSpace(alg_params):
        search_space = []
        for key, val in alg_params.items():
            if val['type'].lower() == "range":
                search_space.append(RangeParameter(name = key, 
                                                   lower = val['lower'], 
                                                   upper = val['upper'], 
                                                   parameter_type = ParameterType.FLOAT if val['value_type'].lower() == 'float' else ParameterType.INT))
            elif val['type'].lower() == "choice":
                search_space.append(ChoiceParameter(name = key, 
                                                    values = val['values'], 
                                                    parameter_type = ParameterType.INT if val['value_type'].lower() == 'int' else ParameterType.STRING))
            else:
                raise Exception("{} is an inproper input for the hyperparamater {}".format(val['type'], key))
                
        assert len(search_space) == len(alg_params), "The searchspace returned does not match the number of hyperparameters provided."
        return SearchSpace(parameters = search_space)

            
    def cluster(self, df, bo_runs = 10, trial_runs = 10):
        
        self.df = df
        self.data_shape = df.shape
        self.distances  = pdist(df)
        
        #set clustering algorthm set
        self.algorithms = [
            ("K-Means",
                 KMeans(), 
                 dict(n_clusters = 
                      dict(
                          upper = 12,
                          lower = 3,
                          type = "range", 
                          value_type = "int"),
                      n_init = 
                      dict(
                          upper = 20,
                          lower = 5,
                          type = "range", 
                          value_type = "int"),
                  )
             ),
            ("Mean Shift",
                  MeanShift(), 
                  dict(max_iter = 
                      dict(
                          upper = self.data_shape[0],
                          lower = 100,
                          type = "range", 
                          value_type = "int"),
                  ),
             ),
            ("Affinity Propgation",
                 AffinityPropagation(), 
                 dict(damping = 
                      dict(
                          upper = 0.99,
                          lower = 0.51,
                          type  = "range", 
                          value_type = "float"),
                     max_iter = 
                      dict(
                          upper = self.data_shape[0],
                          lower = 100,
                          type = "range", 
                          value_type = "int"),
                      convergence_iter =
                      dict(
                          type = "choice", 
                          values = [20, 30, 40, 50],
                          value_type = "int"),
                  ),
             ),
            ("Spectral Clustering",
                 SpectralClustering(),
                 dict(n_clusters = 
                      dict(
                          upper = 12,
                          lower = 3,
                          type = "range", 
                          value_type = "int"),
                      n_components =
                      dict(
                          upper = int(self.data_shape[1]/2),
                          lower = 3,
                          type = "range", 
                          value_type = "int"),
                  ),
             ),
            ("Agglomerative Clustering", 
                 AgglomerativeClustering(),
                 dict(n_clusters = 
                      dict(
                          upper = 12,
                          lower = 3,
                          type = "range", 
                          value_type = "int")
                  ),
             ),
            ("DBScan",
                 DBSCAN(), 
                 dict(eps = 
                      dict(
                          upper = np.percentile(self.distances, 15),
                          lower = 0.01,
                          type = "range", 
                          value_type = "float",
                          log_scale = True),
                     min_samples = 
                      dict(
                          upper = int(self.data_shape[0]*0.2),                         
                          lower = int(self.data_shape[0]*0.05),
                          type = "range", 
                          value_type = "int"),
                  ),
             ),
            ("Optics",
                 OPTICS(), 
                 dict(min_samples = 
                      dict(
                          upper = int(self.data_shape[0]*0.2),                         
                          lower = int(self.data_shape[0]*0.05),
                          type = "range", 
                          value_type = "int"),
                     max_eps = 
                      dict(
                          upper = np.percentile(self.distances, 20),                      
                          lower = 0.05,
                          type = "range", 
                          value_type = "float",
                          log_scale = True),
                  ),
             ),
            ("GaussianMixture",
                 GaussianMixture(),
                 dict(n_components = 
                      dict(
                          upper = 12,                          
                          lower = 3,
                          type = "range", 
                          value_type = "int",),
                     max_iter = 
                      dict(
                          upper = 4*self.data_shape[0],
                          lower = self.data_shape[0],
                          type = "range", 
                          value_type = "int"),
                  ),
             ),
        ]

        #intialize AX Client and begin forloop for each model type 
        self.cluster_results_ = dict()
        for alg in self.algorithms:

            name = alg[0]
            self.model = alg
            
            #intialize experiment
            exp = SimpleExperiment(
                name=name,
                search_space = self.generateSearchSpace(alg[2]),
                evaluation_function = self.sklearnEvalFunction,
                objective_name = "cluster_eval", 
                minimize=True)
            
            #initialize random sample
            sobol = Models.SOBOL(exp.search_space)

            for i in range(trial_runs):
                exp.new_trial(generator_run=sobol.gen(1))
                
            #initialize BO search
            for i in tqdm(range(bo_runs), desc = "GP+EI Optimization Batch - {}".format(name)):
                gpei = Models.BOTORCH(experiment=exp, data=exp.eval())
                exp.new_trial(generator_run=gpei.gen(1))
        
            self.cluster_results_[alg[0]] = dict(model = alg, experiment = exp)

        return self.cluster_results_


from sklearn.datasets import make_blobs
blobs, labels = make_blobs(n_samples=1000, n_features=10, centers = 5)

cluster = ClusterEnesemble()
vals = cluster.cluster(blobs)
```

**Comment by WolVecz** [comment]
Apparently float("inf") is not a recognized value in PyTorch.

**Comment by ldworkin** [comment]
Oh wow, today I learned! Glad you were able to resolve this. Please let us know if you have any other questions.
