### ISSUE TITLE
ALEBO Memory problem

### ISSUE THREAD

**Issue by Pzmijewski** [facebook/Ax#442]
Hello,

i started  a few ALEBO experiments on a Linux VM (2 CPUs, 8GB RAM) at the cloud. The ALEBO-Parameters of two of them are the following:

Exp1:
D=60
d=14
n_total = 300
n_init = 250

Exp2:
D=60
d=14
n_total = 500
n_init = 350

After the init trials (SOBOL) ran I got the following error:

Exp1:
`RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 12500000000 bytes. Error code 12 (Cannot allocate memory)`

Exp2:
`RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 24500000000 bytes. Error code 12 (Cannot allocate memory)`

The root of the error is the same for both:

```
[ERROR 12-06 15:58:21] ax.service.managed_loop: Encountered exception during optimization: 
Traceback (most recent call last):
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/ax/service/managed_loop.py", line 170, in full_run
    self.run_trial()
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/ax/service/managed_loop.py", line 148, in run_trial
    experiment=self.experiment
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/ax/modelbridge/generation_strategy.py", line 384, in gen
    keywords=get_function_argument_names(model.gen),
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/ax/modelbridge/base.py", line 627, in gen
    model_gen_options=model_gen_options,
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/ax/modelbridge/array.py", line 226, in _gen
    target_fidelities=target_fidelities,
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/ax/modelbridge/torch.py", line 211, in _model_gen
    target_fidelities=target_fidelities,
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/ax/models/torch/alebo.py", line 660, in gen
    model_gen_options=model_gen_options,
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/ax/models/torch/botorch.py", line 371, in gen
    **optimizer_options,
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/ax/models/torch/alebo.py", line 500, in alebo_acqf_optimizer
    alpha = acq_function(Yrnd)
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/botorch/utils/transforms.py", line 198, in decorated
    return method(cls, X, **kwargs)
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/botorch/utils/transforms.py", line 169, in decorated
    return method(cls, X, **kwargs)
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/botorch/acquisition/monte_carlo.py", line 243, in forward
    posterior = self.model.posterior(X_full)
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/botorch/models/gpytorch.py", line 500, in posterior
    mvns = self(*[X for _ in range(self.num_outputs)])
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/gpytorch/models/model_list.py", line 83, in __call__
    return [model.__call__(*args_, **kwargs) for model, args_ in zip(self.models, _get_tensor_args(*args))]
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/gpytorch/models/model_list.py", line 83, in <listcomp>
    return [model.__call__(*args_, **kwargs) for model, args_ in zip(self.models, _get_tensor_args(*args))]
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/ax/models/torch/alebo.py", line 162, in __call__
    mvn_b = super().__call__(x)
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/gpytorch/models/exact_gp.py", line 328, in __call__
    predictive_mean, predictive_covar = self.prediction_strategy.exact_prediction(full_mean, full_covar)
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/gpytorch/models/exact_prediction_strategies.py", line 318, in exact_prediction
    self.exact_predictive_covar(test_test_covar, test_train_covar),
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/gpytorch/models/exact_prediction_strategies.py", line 384, in exact_predictive_covar
    covar_inv_quad_form_root = self._exact_predictive_covar_inv_quad_form_root(precomputed_cache, test_train_covar)
  File "/home/nicolas_meseth/virtual_env/lib/python3.7/site-packages/gpytorch/models/exact_prediction_strategies.py", line 100, in _exact_predictive_covar_inv_quad_form_root
    return test_train_covar.matmul(precomputed_cache)
```

Is it correct that there should be a cache up to 12.5 GB / 24.5 GB or is there a memory leak or something?

thank you in advance

Philipp

**Comment by adamobeng** [comment]
Thanks for posting, Philipp. Let me look into this and get back to you.

**Comment by bletham** [comment]
Hi, I don't know that I can suggest much besides increasing the RAM. GP regression (as in gpytorch) can be a bit RAM heavy. The problem specs you described (dimensionality, number of data points) are certainly within the scope of what should work. Most of the benchmarking that I've done has used machines with 16Gb of RAM, though with the experiments with 500 points were on a machine with 48gb of RAM so I can't say for sure what the minimum requirement there is.

**Comment by lena-kashtelyan** [comment]
Closing this one, as it seems that it has been answered and this is not something we plan on fixing on our side. @Pzmijewski, please feel free to reopen if you have any follow-ups!
