### ISSUE TITLE
Import AxClient fails if SQLAlchemy not installed

### ISSUE THREAD

**Issue by jieru-hu** [facebook/Ax#662]
This seems to only happen on the latest version of ax (0.2.1) released earlier this week.

```
$ pip show ax-platform
Name: ax-platform
Version: 0.2.1

# run python interpreter
>>> from ax.service.ax_client import AxClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/circleci/miniconda3/envs/hydra/lib/python3.8/site-packages/ax/service/ax_client.py", line 47, in <module>
    from ax.service.utils.with_db_settings_base import DBSettings, WithDBSettingsBase
  File "/home/circleci/miniconda3/envs/hydra/lib/python3.8/site-packages/ax/service/utils/with_db_settings_base.py", line 16, in <module>
    from ax.storage.sqa_store.decoder import Decoder
  File "/home/circleci/miniconda3/envs/hydra/lib/python3.8/site-packages/ax/storage/sqa_store/__init__.py", line 9, in <module>
    from ax.storage.sqa_store import validation
  File "/home/circleci/miniconda3/envs/hydra/lib/python3.8/site-packages/ax/storage/sqa_store/validation.py", line 9, in <module>
    from ax.storage.sqa_store.db import SQABase
  File "/home/circleci/miniconda3/envs/hydra/lib/python3.8/site-packages/ax/storage/sqa_store/db.py", line 12, in <module>
    from sqlalchemy import create_engine
ModuleNotFoundError: No module named 'sqlalchemy'

# install the previous version
$ pip show ax-platform
Name: ax-platform
Version: 0.2.0

# works 
$ python
Python 3.8.11 (default, Aug  3 2021, 15:09:35) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ax.service.ax_client import AxClient


```

**Comment by danielcohenlive** [comment]
Thanks for flagging this @jieru-hu.  We're looking into it

**Comment by danielcohenlive** [comment]
It looks something was introduced that makes `sqlalchemy` required.  We have a fix coming, but for now you can run this install as a workaround
```
pip install ax-platform[mysql]==0.2.1
```

**Comment by danielcohenlive** [comment]
We have a fix merged to master, which we'll be releasing soon, possibly this week

**Comment by lena-kashtelyan** [comment]
Stable version 0.2.2 is out now and takes care of this issue.
