### ISSUE TITLE
Second trial fails in optimize

### ISSUE THREAD

**Issue by SohamPardeshi** [facebook/Ax#757]
When running `optimize`, the second trial always fails. Not sure if this is a known error or whether I should provide more details about what I am trying to do.

```
[INFO 12-15 06:08:21] ax.service.managed_loop: Running optimization trial 3...
[ERROR 12-15 06:08:21] ax.service.managed_loop: Encountered exception during optimization: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ax/service/managed_loop.py", line 229, in full_run
    self.run_trial()
  File "/usr/local/lib/python3.7/dist-packages/ax/utils/common/executils.py", line 147, in actual_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ax/service/managed_loop.py", line 203, in run_trial
    trial = self._get_new_trial()
  File "/usr/local/lib/python3.7/dist-packages/ax/service/managed_loop.py", line 164, in _get_new_trial
    experiment=self.experiment
  File "/usr/local/lib/python3.7/dist-packages/ax/modelbridge/generation_strategy.py", line 444, in gen
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/ax/modelbridge/generation_strategy.py", line 561, in _gen_multiple
    self._set_or_update_current_model(data=data)
  File "/usr/local/lib/python3.7/dist-packages/ax/modelbridge/generation_strategy.py", line 634, in _set_or_update_current_model
    self._set_current_model(data=data)
  File "/usr/local/lib/python3.7/dist-packages/ax/modelbridge/generation_strategy.py", line 822, in _set_current_model
    self._set_current_model_from_models_enum(data=data, **model_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ax/modelbridge/generation_strategy.py", line 866, in _set_current_model_from_models_enum
    self._model = self._curr.model(experiment=self.experiment, data=data, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ax/modelbridge/registry.py", line 325, in __call__
    **bridge_kwargs,
  File "/usr/local/lib/python3.7/dist-packages/ax/modelbridge/base.py", line 156, in __init__
    if experiment is not None and data is not None
  File "/usr/local/lib/python3.7/dist-packages/ax/core/observation.py", line 372, in observations_from_data
    include_abandoned=include_abandoned,
  File "/usr/local/lib/python3.7/dist-packages/ax/core/observation.py", line 254, in _observations_from_dataframe
    metadata = trial._get_candidate_metadata(arm_name) or {}
  File "/usr/local/lib/python3.7/dist-packages/ax/core/trial.py", line 229, in _get_candidate_metadata
    f"Arm by name {arm_name} is not part of trial #{self.index}."
ValueError: Arm by name 2_0 is not part of trial #1.
```

**Comment by lena-kashtelyan** [comment]
Hi @SohamPardeshi, may I ask which version of Ax you are on (if not latest: 0.2.2, please update and try again)? Thank you in advance!

**Comment by lena-kashtelyan** [comment]
Closing this issue as inactive; please reopen when you add the requested info, @SohamPardeshi!
