### ISSUE TITLE
ValueError: numpy.ufunc size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by glenn-jocher** [facebook/Ax#82]
When running the hyperparameter tuning tutorial, using anaconda 3.7 and installing with `pip install ax-platform`
https://ax.dev/tutorials/tune_cnn.html

```bash
/Users/glennjocher/.conda/envs/yolov3/bin/python /Users/glennjocher/PycharmProjects/yolov3/tune_cnn.py
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/yolov3/tune_cnn.py", line 6, in <module>
    from ax.service.managed_loop import optimize
  File "/Users/glennjocher/.conda/envs/yolov3/lib/python3.7/site-packages/ax/__init__.py", line 5, in <module>
    from ax.modelbridge import Models
  File "/Users/glennjocher/.conda/envs/yolov3/lib/python3.7/site-packages/ax/modelbridge/__init__.py", line 6, in <module>
    from ax.modelbridge.factory import (
  File "/Users/glennjocher/.conda/envs/yolov3/lib/python3.7/site-packages/ax/modelbridge/factory.py", line 12, in <module>
    from ax.modelbridge.discrete import DiscreteModelBridge
  File "/Users/glennjocher/.conda/envs/yolov3/lib/python3.7/site-packages/ax/modelbridge/discrete.py", line 18, in <module>
    from ax.models.discrete_base import DiscreteModel
  File "/Users/glennjocher/.conda/envs/yolov3/lib/python3.7/site-packages/ax/models/__init__.py", line 4, in <module>
    from ax.models.random.sobol import SobolGenerator
  File "/Users/glennjocher/.conda/envs/yolov3/lib/python3.7/site-packages/ax/models/random/sobol.py", line 10, in <module>
    from ax.utils.stats.sobol import SobolEngine  # pyre-ignore: Not handling .pyx properly
  File "__init__.pxd", line 918, in init ax.utils.stats.sobol
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

Process finished with exit code 1
```

**Comment by lena-kashtelyan** [comment]
Hey, @glenn-jocher, thank you for raising this! Which version of numpy are you on?

**Comment by glenn-jocher** [comment]
np.__version__
'1.15.4'

**Comment by lena-kashtelyan** [comment]
That is most likely the reason; seems like older numpy packages had this problem. Would it be possible for you to update numpy?

**Comment by glenn-jocher** [comment]
@lena-kashtelyan Hi thanks, I upgraded with `conda update numpy` and the error message is fixed! Thank you.
