### ISSUE TITLE
Small and medium sized dataset suitability for Ax, with GPU computing. Is 15000 too many?

### ISSUE THREAD

**Issue by sgbaird** [facebook/Ax#888]
I am using ~15000 samples across 8 dimensions (15000 x 8). Incidentally, I am also using Raytune per the Ax tutorial. New samples are somewhat expensive, around 20 min to 20 hrs per simulation based on the chosen parameters. Hoping to do somewhere between 100-1000 iterations of adaptive design, and `max_parallel` of somewhere between 8 and 12, based on number of CPUs available. 

Does this seem feasible with consumer hardware (e.g. RTX 2060-Ti) and less than a week of runtime?

Will probably do some forecasting to see how the runtime scales with number of training points for this problem and use that to assess whether or not to switch to a genetic algorithm for this particular problem (or downselect training points to a more manageable size). Figured it was worth asking if anyone has had experience running with over 10000 initialized points.

**Comment by sgbaird** [comment]
Have been running out of memory (16 GB CPU RAM) for ~3000 trials with the 8 dimensions, single objective. Going to try the suggestion related to BoTorch model parameters in https://github.com/facebook/Ax/issues/674#issuecomment-920163649

**Comment by qingfeng10** [comment]
Hey @sgbaird, thanks for trying Ax!  15000 is indeed a large sample size for GP model fitting and also acquisition function optimization. GPU may speed up computation but the memory would still be a an issue. I haven' t experimented such large sample size, so I don't know the exact upper bound is.  cc @danielrjiang @dme65 @saitcakmak check with other researchers who might know this. 

Following your latest trial (~3000 trials with the 8 dimensions, single objective), do you know in which step you get out-of-memory?  Is that be part of optimizing acquisition function? If so, the suggestions in https://github.com/facebook/Ax/issues/674#issuecomment-920163649 make a lot sense.  

> I remember that the overhead of SAASBO scales cubically with the number of datapoints. How does the overhead scale with the number of datapoints for the GPEI model? 

Regarding this, GPEI will do a better job in scaling with the num of data points, because GPEI does not have to marginalize across hyper-parameter samples from MCMC as SAASBO.

**Comment by saitcakmak** [comment]
Yeah, 15000 is definitely gonna be a challenge. If you can make the model fitting work, then passing in argument similar to the linked comment would help. One comment on that is rather than using `{"optimizer_options": {"num_restarts": 10, "raw_samples": 256}}` which reduce the optimization budget and may affect the performance, I'd recommend using `{"optimizer_options": {"options": {"batch_limit": <some small integer, less than num_restarts>}}}` which reduce the number of solutions being evaluated in parallel and reduce the memory usage (which is your likely bottleneck) in return for increased runtime. 

The cubic scaling you mentioned is a feature of exact GP inference, so it is an issue with standard GPs as well. There are approximate computations that you can enable via gpytorch settings (https://docs.gpytorch.ai/en/stable/settings.html) that are designed to help with the cubic scalability issue (but they may not be as robust). I don't have much experience with these, @dme65 might tell you more. If you wanted to experiment with these, you can just wrap your BO loop with the desired context manager:
```
import gpytorch

with gpytorch.settings.fast_computations():
    <the Ax loop goes in here>
```

**Comment by sgbaird** [comment]
Here is the stack trace with CUDA enabled, `1000` training samples across `8` dimensions with `{"batch_limit": 1}` (aside: it sounded like a low number was supposed to be less memory usage) as described above:
```python
    gs = GenerationStrategy(
        steps=[
            # 1. Initialization step (does not require pre-existing data and is well-suited for
            # initial sampling of the search space)
            GenerationStep(
                model=Models.SOBOL,
                num_trials=n_sobol,
                # min_trials_observed=n_sobol,  # How many trials need to be completed to move to next model
                max_parallelism=max_parallel,  # Max parallelism for this step
                model_kwargs={"seed": 999},  # Any kwargs you want passed into the model
                model_gen_kwargs={},  # Any kwargs you want passed to `modelbridge.gen`
            ),
            # 2. Bayesian optimization step (requires data obtained from previous phase and learns
            # from all data available at the time of each new candidate generation call)
            GenerationStep(
                model=Models.BOTORCH_MODULAR,
                num_trials=-1,  # No limitation on how many trials should be produced from this step
                model_kwargs={
                    "fit_out_of_design": True,
                    "torch_device": torch_device,
                    "acquisition_options": {
                        "optimizer_options": {"options": {"batch_limit": 1}}
                    },
                },
                max_parallelism=max_parallel,  # Parallelism limit for this step, often lower than for Sobol
                # More on parallelism vs. required samples in BayesOpt:
                # https://ax.dev/docs/bayesopt.html#tradeoff-between-parallelism-and-total-number-of-trials
            ),
        ]
    )

    ax_client = AxClient(
        generation_strategy=gs,
        enforce_sequential_optimization=False,
        verbose_logging=False,
    )
```
```bash
Cholesky errors typically occur when the same or very similar arms are suggested repeatedly. This can mean the model has 
already converged and you should avoid running further trials. It will also help to convert integer or categorical parameters to 
float ranges where reasonable.
[ERROR 03-31 20:30:12] ax.service.ax_client: CUDA out of memory. Tried to allocate 7.65 GiB (GPU 0; 6.00 GiB total capacity; 
660.90 MiB already allocated; 3.71 GiB free; 690.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated 
memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and 
PYTORCH_CUDA_ALLOC_CONF 
Traceback (most recent call last):
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\utils\common\executils.py", line 169, in handle_exceptions_in_retries    
    yield  # Perform action within the context manager.
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\utils\common\executils.py", line 147, in actual_wrapper
    return func(*args, **kwargs)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\service\ax_client.py", line 379, in get_next_trial
    generator_run=self._gen_new_generator_run(), ttl_seconds=ttl_seconds
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\service\ax_client.py", line 1338, in _gen_new_generator_run
    return not_none(self.generation_strategy).gen(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\generation_strategy.py", line 330, in gen
    return self._gen_multiple(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\generation_strategy.py", line 471, in _gen_multiple
    generator_run = _gen_from_generation_step( 
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\generation_strategy.py", line 833, in _gen_from_generation_step
    generator_run = generation_step.gen(       
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\generation_node.py", line 167, in gen
    return model_spec.gen(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\model_spec.py", line 204, in gen
    return fitted_model.gen(**model_gen_kwargs)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\base.py", line 674, in gen
    observation_features, weights, best_obsf, gen_metadata = self._gen(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\array.py", line 277, in _gen
    X, w, gen_metadata, candidate_metadata = self._model_gen(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\torch.py", line 275, in _model_gen
    X, w, gen_metadata, candidate_metadata = not_none(self.model).gen(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\models\torch\botorch_modular\model.py", line 284, in gen
    candidates, expected_acquisition_value = acqf.optimize(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\models\torch\botorch_modular\acquisition.py", line 275, in optimize      
    return optimize_acqf(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\botorch\optim\optimize.py", line 199, in optimize_acqf
    batch_initial_conditions = ic_gen(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\botorch\optim\initializers.py", line 183, in gen_batch_initial_conditions   
    Y_rnd_curr = acq_function(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)      
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\botorch\utils\transforms.py", line 270, in decorated
    return method(cls, X, **kwargs)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\botorch\utils\transforms.py", line 229, in decorated
    output = method(acqf, X, *args, **kwargs)  
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\botorch\acquisition\monte_carlo.py", line 371, in forward
    posterior = self.model.posterior(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\botorch\models\gpytorch.py", line 341, in posterior
    mvn = self(X)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\models\exact_gp.py", line 319, in __call__
    predictive_mean, predictive_covar = self.prediction_strategy.exact_prediction(full_mean, full_covar)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\models\exact_prediction_strategies.py", line 262, in exact_prediction
    self.exact_predictive_mean(test_mean, test_train_covar),
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\models\exact_prediction_strategies.py", line 280, in exact_predictive_mean
    res = (test_train_covar @ self.mean_cache.unsqueeze(-1)).squeeze(-1)
    res = self.kernel(  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\kernels\kernel.py", line 402, in __call__
    res = lazify(super(Kernel, self).__call__(x1_, x2_, last_dim_is_batch=last_dim_is_batch, **params))
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\module.py", line 30, in __call__    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\kernels\scale_kernel.py", line 103, in forward    orig_output = self.base_kernel.forward(x1, x2, diag=diag, last_dim_is_batch=last_dim_is_batch, **params)  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\kernels\matern_kernel.py", line 102, in forward    distance = self.covar_dist(x1_, x2_, diag=diag, **params)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\kernels\kernel.py", line 333, in covar_dist    res = self.distance_module._dist(x1, x2, postprocess, x1_eq_x2)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\kernels\kernel.py", line 56, in _dist
    res = self._sq_dist(x1, x2, postprocess=False, x1_eq_x2=x1_eq_x2)  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\kernels\kernel.py", line 45, in _sq_dist
    res = x1_.matmul(x2_.transpose(-2, -1))RuntimeError: CUDA out of memory. Tried to allocate 7.65 GiB (GPU 0; 6.00 GiB total capacity; 660.90 MiB already allocated; 3.71 GiB free; 690.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[ERROR 03-31 20:30:12] ax.service.ax_client: CUDA out of memory. Tried to allocate 7.65 GiB (GPU 0; 6.00 GiB total capacity; 660.90 MiB already allocated; 3.71 GiB free; 690.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF 
Traceback (most recent call last):
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\utils\common\executils.py", line 169, in handle_exceptions_in_retries    
    yield  # Perform action within the context manager.
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\utils\common\executils.py", line 147, in actual_wrapper
    return func(*args, **kwargs)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\service\ax_client.py", line 379, in get_next_trial
    generator_run=self._gen_new_generator_run(), ttl_seconds=ttl_seconds
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\service\ax_client.py", line 1338, in _gen_new_generator_run
    return not_none(self.generation_strategy).gen(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\generation_strategy.py", line 330, in gen
    return self._gen_multiple(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\generation_strategy.py", line 471, in _gen_multiple
    generator_run = _gen_from_generation_step( 
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\generation_strategy.py", line 833, in _gen_from_generation_step
    generator_run = generation_step.gen(       
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\generation_node.py", line 167, in gen
    return model_spec.gen(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\model_spec.py", line 204, in gen
    return fitted_model.gen(**model_gen_kwargs)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\base.py", line 674, in gen
    observation_features, weights, best_obsf, gen_metadata = self._gen(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\array.py", line 277, in _gen
    X, w, gen_metadata, candidate_metadata = self._model_gen(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\modelbridge\torch.py", line 275, in _model_gen
    X, w, gen_metadata, candidate_metadata = not_none(self.model).gen(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\models\torch\botorch_modular\model.py", line 284, in gen
    candidates, expected_acquisition_value = acqf.optimize(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\ax\models\torch\botorch_modular\acquisition.py", line 275, in optimize      
    return optimize_acqf(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\botorch\optim\optimize.py", line 199, in optimize_acqf
    batch_initial_conditions = ic_gen(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\botorch\optim\initializers.py", line 183, in gen_batch_initial_conditions   
    Y_rnd_curr = acq_function(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)      
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\botorch\utils\transforms.py", line 270, in decorated
    return method(cls, X, **kwargs)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\botorch\utils\transforms.py", line 229, in decorated
    output = method(acqf, X, *args, **kwargs)  
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\botorch\acquisition\monte_carlo.py", line 371, in forward
    posterior = self.model.posterior(
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\botorch\models\gpytorch.py", line 341, in posterior
    mvn = self(X)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\models\exact_gp.py", line 319, in __call__
    predictive_mean, predictive_covar = self.prediction_strategy.exact_prediction(full_mean, full_covar)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\models\exact_prediction_strategies.py", line 262, in exact_prediction
    self.exact_predictive_mean(test_mean, test_train_covar),
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\models\exact_prediction_strategies.py", line 280, in exact_predictive_mean
    res = (test_train_covar @ self.mean_cache.unsqueeze(-1)).squeeze(-1)
    res = self.kernel(  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\kernels\kernel.py", line 402, in __call__
    res = lazify(super(Kernel, self).__call__(x1_, x2_, last_dim_is_batch=last_dim_is_batch, **params))
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\module.py", line 30, in __call__    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\kernels\scale_kernel.py", line 103, in forward    orig_output = self.base_kernel.forward(x1, x2, diag=diag, last_dim_is_batch=last_dim_is_batch, **params)  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\kernels\matern_kernel.py", line 102, in forward    distance = self.covar_dist(x1_, x2_, diag=diag, **params)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\kernels\kernel.py", line 333, in covar_dist    res = self.distance_module._dist(x1, x2, postprocess, x1_eq_x2)
  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\kernels\kernel.py", line 56, in _dist
    res = self._sq_dist(x1, x2, postprocess=False, x1_eq_x2=x1_eq_x2)  File "C:\Users\sterg\Miniconda3\envs\packing\lib\site-packages\gpytorch\kernels\kernel.py", line 45, in _sq_dist
    res = x1_.matmul(x2_.transpose(-2, -1))
RuntimeError: CUDA out of memory. Tried to allocate 7.65 GiB (GPU 0; 6.00 GiB total capacity; 660.90 MiB already allocated; 
3.71 GiB free; 690.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting 
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

##
Then the message using the CPU (call stack seems to be identical), `3000` points, `8` dimensions, and `{"batch_limit": 1}`:
> RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 73801744384 bytes.

`73801744384` bytes == `73.8` GB.

Based on some of the functions shown, I take it this error occurs during generation. Happy to post a reproducer/MWE, just say the word - however, I'm wondering if this will turn into somewhat of a losing battle.

If I set `{"batch_limit": 2}`, I actually get the same error:
```
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:81] data. DefaultCPUAllocator: not enough memory: you tried to allocate 73801744384 bytes.
```
Which makes me wonder if I'm passing it correctly (see above):
```python
...
                model_kwargs={
                    "fit_out_of_design": True,
                    "torch_device": torch_device,
                    "acquisition_options": {
                        "optimizer_options": {"options": {"batch_limit": 1}}
                    },
                },
...
```
Should this be going to `model_gen_kwargs` instead?

**Comment by sgbaird** [comment]
For most of the materials science problems that I've been working on using Ax as the optimization tool, the dataset size is much smaller. For this task, I may try out [Dragonfly](https://github.com/dragonfly/dragonfly) which seems geared towards large problems, or downselect the number of data points.

Also, @saitcakmak I wasn't aware of `fastcomputations()` within `gpytorch`. Thanks for letting me know about this! Unfortunately, I run into an error using the snippet you linked:
```python
RuntimeError: shape '[-1, 100]' is invalid for input of size 512512
rsample (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\gpytorch\distributions\multivariate_normal.py:202)
rsample (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\botorch\posteriors\gpytorch.py:100)
forward (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\botorch\sampling\samplers.py:93)
_call_impl (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\torch\nn\modules\module.py:1110)
__init__ (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\botorch\acquisition\monte_carlo.py:272)
__init__ (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\models\torch\botorch_modular\acquisition.py:190)
_instantiate_acquisition (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\models\torch\botorch_modular\model.py:452)
gen (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\models\torch\botorch_modular\model.py:273)
_model_gen (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\modelbridge\torch.py:275)
_gen (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\modelbridge\array.py:277)
gen (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\modelbridge\base.py:674)
gen (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\modelbridge\model_spec.py:204)
gen (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\modelbridge\generation_node.py:167)
_gen_from_generation_step (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\modelbridge\generation_strategy.py:833)
_gen_multiple (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\modelbridge\generation_strategy.py:471)
gen (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\modelbridge\generation_strategy.py:330)
_gen_new_generator_run (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\service\ax_client.py:1338)
get_next_trial (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\service\ax_client.py:379)
actual_wrapper (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\utils\common\executils.py:147)
handle_exceptions_in_retries (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\utils\common\executils.py:197)
handle_exceptions_in_retries (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\utils\common\executils.py:197)
__exit__ (c:\Users\sterg\miniconda3\envs\packing\Lib\contextlib.py:131)
actual_wrapper (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ax\utils\common\executils.py:147)
suggest (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ray\tune\suggest\ax.py:266)
suggest (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ray\tune\suggest\suggestion.py:506)
create_trial_if_possible (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ray\tune\suggest\search_generator.py:97)
next_trial (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ray\tune\suggest\search_generator.py:89)
_update_trial_queue (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ray\tune\trial_runner.py:1246)
_get_next_trial (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ray\tune\trial_runner.py:812)
step (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ray\tune\trial_runner.py:662)
run (c:\Users\sterg\miniconda3\envs\packing\Lib\site-packages\ray\tune\tune.py:610)
optimize_ppf (c:\Users\sterg\Documents\GitHub\sparks-baird\bayes-opt-particle-packing\boppf\utils\ax.py:129)
optimize (c:\Users\sterg\Documents\GitHub\sparks-baird\bayes-opt-particle-packing\boppf\boppf.py:53)
<module> (c:\Users\sterg\Documents\GitHub\sparks-baird\bayes-opt-particle-packing\examples\boppf_example.py:45)
_run_code (c:\Users\sterg\miniconda3\envs\packing\Lib\runpy.py:87)
_run_module_code (c:\Users\sterg\miniconda3\envs\packing\Lib\runpy.py:97)
run_path (c:\Users\sterg\miniconda3\envs\packing\Lib\runpy.py:265)
_run_code (c:\Users\sterg\miniconda3\envs\packing\Lib\runpy.py:87)
_run_module_as_main (Current frame) (c:\Users\sterg\miniconda3\envs\packing\Lib\runpy.py:194)
```
I'll keep these approximations/speedups in mind for later if I decide to probe further/try to resolve the error.

**Comment by sgbaird** [comment]
Also might be worth mentioning that the use of GPU (RTX 2060 on my local machine) via `torch.device("cuda")` seems to be a bit slower than on CPU via `torch.device("cpu")`, passed to `GenerationStep` passed to `GenerationStrategy` via:
```python
model_kwargs={"fit_out_of_design": True, "torch_device": torch_device}
```
when tested on dataset sizes somewhat below the threshold of the CUDA OOM errors.

**Comment by saitcakmak** [comment]
So, from the error code in your first reply, it seems like you get through the model fitting stage. The error happens when you try to compute the GP posterior while computing the acquisition function, which is not surprising given that the acquisition function used by default is `qNoisyExpectedImprovement` which is a bit memory intensive. If you were to replace that with `ExpectedImprovement` (the analytic version - I got some errors when I tried this with Ax) or the `qExpectedImprovement`, you'd have better luck. To do so, you can try:
```
from botorch.acquisition import qExpectedImprovement

                model_kwargs={
                    "fit_out_of_design": True,
                    "torch_device": torch_device,
                    "acquisition_options": {
                        "optimizer_options": {"options": {"batch_limit": 1}}
                    },
                    "botorch_acqf_class": qExpectedImprovement,
                },
```

I tested this in BoTorch, essentially replicating what will happen under the hood if you do this with Ax. I did not use any of the gpytorch context manager. Using a P100 GPU (16gb mem) I was able to fit a model on 12k data points and optimize the acquisition function. So, I think you should be able to push this up to a good few thousands of training points with `qExpectedImprovement`.

**Comment by sgbaird** [comment]
@saitcakmak fantastic, thank you for looking into this! I will give it a try (and that's promising to hear that you were able to run 12k points - our group has a machine with better GPUs that I'd be running this on after the testing stage).

**Comment by Balandat** [comment]
Another alternative here would be to try use KeOps. I’m currently off the grid-ish and can’t put together a demo but this could be a starting point: https://github.com/cornellius-gp/gpytorch/blob/master/examples/02_Scalable_Exact_GPs/KeOps_GP_Regression.ipynb

**Comment by sgbaird** [comment]
@MrJasonBear (my colleague) tagging you in case you want to keep up on the discussion

**Comment by sgbaird** [comment]
@saitcakmak tried out your suggestion, and that certainly seems to reduce the memory consumption. I'm still planning to give KeOps a try.

**Comment by lena-kashtelyan** [comment]
Sounds like maybe this has been addressed, but feel free to reopen as needed, @sgbaird! If you do follow up, please do reopen, as it's harder to see comments on closed issues.

**Comment by sgbaird** [comment]
@lena-kashtelyan, I think this is fine to be closed for now. In terms of reopening, I don't think I can on my own. Normally I'd expect a button around here somewhere.

![image](https://user-images.githubusercontent.com/45469701/163632709-0488f95a-6a64-472d-9d20-f47f13b1b358.png)

Looks like I would need to close the issue myself https://stackoverflow.com/a/21333938/13697228
