### ISSUE TITLE
AttributError __enter__ at SAASBO MCMC with Python 3.10

### ISSUE THREAD

**Issue by pehzet** [facebook/Ax#893]
Hey,

the following error occurs when running SAASBO on Python 3.10. I think it might be a problem with Pyro and the newest Python Version.
It can be avoided by using Python 3.8, as commented [at Pyro Github](https://github.com/pyro-ppl/pyro/issues/3018), but I want to address the issue here.

Thank you! You are doing great work!

Phil
_______________________________________________________________________________________
Traceback (most recent call last):
  File "C:\code\black-box-opt-server-api\object_overview.py", line 67, in <module>
    suggest(exp_name, "saasbo")
  File "C:\code\black-box-opt-server-api\server.py", line 50, in suggest
    trial, experiment = suggest_next_trial(experiment, algorithm_config)
  File "C:\code\black-box-opt-server-api\algorithms\saasbo\saasbo_stepwise.py", line 92, in suggest_next_trial
    m = Models.FULLYBAYESIAN(
  File "C:\code\black-box-opt-server-api\bbo-env\lib\site-packages\ax\modelbridge\registry.py", line 342, in __call__
    model_bridge = bridge_class(
  File "C:\code\black-box-opt-server-api\bbo-env\lib\site-packages\ax\modelbridge\torch.py", line 99, in __init__
    super().__init__(
  File "C:\code\black-box-opt-server-api\bbo-env\lib\site-packages\ax\modelbridge\base.py", line 181, in __init__
    self._fit(
  File "C:\code\black-box-opt-server-api\bbo-env\lib\site-packages\ax\modelbridge\torch.py", line 131, in _fit
    super()._fit(
  File "C:\code\black-box-opt-server-api\bbo-env\lib\site-packages\ax\modelbridge\array.py", line 103, in _fit
    self._model_fit(
  File "C:\code\black-box-opt-server-api\bbo-env\lib\site-packages\ax\modelbridge\torch.py", line 197, in _model_fit
    self.model.fit(
  File "C:\code\black-box-opt-server-api\bbo-env\lib\site-packages\ax\models\torch\botorch.py", line 296, in fit
    self.model = self.model_constructor(  # pyre-ignore [28]
  File "C:\code\black-box-opt-server-api\bbo-env\lib\site-packages\ax\models\torch\fully_bayesian.py", line 346, in get_and_fit_model_mcmc
    model, mcmc_samples_list = _get_model_mcmc_samples(
  File "C:\code\black-box-opt-server-api\bbo-env\lib\site-packages\ax\models\torch\fully_bayesian.py", line 302, in _get_model_mcmc_samples
    mcmc_samples = run_inference(
  File "C:\code\black-box-opt-server-api\bbo-env\lib\site-packages\ax\models\torch\fully_bayesian.py", line 407, in run_inference
    mcmc.run(
  File "C:\code\black-box-opt-server-api\bbo-env\lib\site-packages\pyro\poutine\messenger.py", line 11, in _context_wrap
    with context:
AttributeError: __enter__

**Comment by lena-kashtelyan** [comment]
@dme65 will have the most context on this one, so we'll hear from him soon on how to proceed about this!

**Comment by dme65** [comment]
Hi @pehzet, It looks like this isn't an issue with Ax but rather Pyro not supporting Python 3.10. I commented on https://github.com/pyro-ppl/pyro/issues/3018 again.

**Comment by lena-kashtelyan** [comment]
We'll leave this open until the underlying Pyro issue is resolved!
