### ISSUE TITLE
[Question/Issue] Choice parameters don't work with string values

### ISSUE THREAD

**Issue by Irynei** [facebook/Ax#93]
I was trying to do optimization using choice parameters. Here is a simple example:
```python
best_parameters, values, experiment, model = optimize(
    parameters=[
        {'name': 'categorical', 'type': 'choice', 'values': ['foo', 'bar']}
    ],
    evaluation_function=objective,
    minimize=True,
)
```
And I got the following error:

> Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ax/service/managed_loop.py", line 206, in optimize
    loop.full_run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ax/service/managed_loop.py", line 150, in full_run
    self.run_trial()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ax/service/managed_loop.py", line 130, in run_trial
    experiment=self.experiment, new_data=dat
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ax/core/experiment.py", line 446, in new_trial
    experiment=self, trial_type=trial_type, generator_run=generator_run
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ax/core/trial.py", line 38, in __init__
    self.add_generator_run(generator_run=generator_run)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ax/core/base_trial.py", line 85, in _immutable_once_run
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ax/core/trial.py", line 87, in add_generator_run
    generator_run.arms[0].parameters, raise_error=True
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ax/core/search_space.py", line 192, in check_types
    f"{value} is not a valid value for "
ValueError: bar is not a valid value for parameter ChoiceParameter(name='categorical', parameter_type=STRING, values=['foo', 'bar'])

Digging into that, I found that the problem was with the `one_hot` transformer, it changed the type of string values to `numpy.str_` and hence, the ValueError was raised.

I see that this is already fixed in [this](https://github.com/facebook/Ax/commit/8f7fb1396480b55f2ed93b94ba36808ddbd6c289)  commit, but it's not available in the currently latest [0.1.1](https://github.com/facebook/Ax/tree/0.1.1) tag.

Could you please provide information when the new release is going to be?
Thank you!

**Comment by ldworkin** [comment]
Hi @Irynei! I think we're planning to do a new release tomorrow :) In the meantime (or in the future) you can try pulling from master and then doing `pip install -e .`.

**Comment by Irynei** [comment]
Cool, thanks.

**Comment by ldworkin** [comment]
Closing, since this should be in our current release (0.1.2)
