### ISSUE TITLE
Multi-Objective Optimization with Scheduler API

### ISSUE THREAD

**Issue by dreamoir** [facebook/Ax#934]
Hi,
**The Multi-Objective Optimization (MOO) tutorial uses the service API - is it compatible with the Scheduler API?** 

I've implemented the Scheduler API successfully using a Sobol+GPEI generation strategy as follows:
```

def make_experiment_with_runner_and_metric():
    parameters=[]
    for param in inputs:
      if param=='sh': #choice parameter exception for PSD and surface roughness
           parameters.append(ChoiceParameter(name=param, values=['0','1','2'], parameter_type=ParameterType.STRING))
      else:
          parameters.append(RangeParameter(
              name=param, parameter_type=ParameterType.FLOAT, lower=lower[param], upper=upper[param]))
          
      optimization_configuration = OptimizationConfig(
      objective=Objective(
          metric=CoverageMetric(name="coverage_metric")),
  )
      return Experiment(name="single_task",
                                    search_space=SearchSpace(parameters=parameters),
                                    optimization_config=optimization_configuration,
                                    runner=JobRunner(),
                                    is_test=False,)

gs = GenerationStrategy(
    steps=[
        GenerationStep(
            model=Models.SOBOL,
            num_trials=5,  # How many trials should be produced from this generation step
            min_trials_observed=3, # How many trials need to be completed to move to next model
            max_parallelism=5,  # Max parallelism for this step
            model_kwargs={"seed": 999},  # Any kwargs you want passed into the model
            model_gen_kwargs={},  # Any kwargs you want passed to `modelbridge.gen`
        ),
        GenerationStep(
            model=Models.GPEI,
            num_trials=15, 
            max_parallelism=5,  
        ),
    ]
)
 experiment = make_experiment_with_runner_and_metric()


scheduler = Scheduler(
experiment=experiment,
generation_strategy=gs,
options=SchedulerOptions(),
)
for i in range(5):
    scheduler.run_n_trials(max_trials=5)
```

However, I am now trying to use MOO, though unsure of how to implement this using the scheduler API.

I've tried to simply switch out the GenerationStep model from Model.GPEI to Model.MOO and using MultiObjectiveOptimizationConfig for the optimization_config as follows:
```
def make_experiment_with_runner_and_metric() -> Experiment:
    parameters=[]
    for param in inputs:
        if param=='sh': #choice parameter exception for PSD and surface roughness
             parameters.append(ChoiceParameter(name=param, values=['0','1','2'], parameter_type=ParameterType.STRING))
        else:
            parameters.append(RangeParameter(
                name=param, parameter_type=ParameterType.FLOAT, lower=lower[param], upper=upper[param]
            ))

    coverage = CoverageMetric(name="coverage_metric",lower_is_better=False)
    roughness = RoughnessMetric(name="roughness_metric",lower_is_better=True)
    mo = MultiObjective(objectives=[Objective(metric=coverage),Objective(metric=roughness)])
    objective_thresholds = [
        ObjectiveThreshold(metric=coverage, bound=[0.0,1.1], relative=False),
        ObjectiveThreshold(metric=roughness, bound=[0.0,70e-6], relative=False),
    ]
    optimization_configuration = MultiObjectiveOptimizationConfig(
        objective=mo,
        objective_thresholds=objective_thresholds,
        )

    return Experiment(
        name="MOO",
        search_space=SearchSpace(parameters=parameters),
        optimization_config=optimization_configuration,
        runner=JobRunner(),
        is_test=False    )

gs = GenerationStrategy(
    steps=[
        GenerationStep(
            model=Models.SOBOL,
            num_trials=5,  # How many trials should be produced from this generation step
            min_trials_observed=3, # How many trials need to be completed to move to next model
            max_parallelism=5,  # Max parallelism for this step
            model_kwargs={"seed": 999},  # Any kwargs you want passed into the model
            model_gen_kwargs={},  # Any kwargs you want passed to `modelbridge.gen`
        ),
        GenerationStep(
            model=Models.MOO,
            num_trials=15, 
            max_parallelism=5,  
        ),
    ]
)
```
 but that returns an error:

```
Traceback (most recent call last):
  File "/home/xxx/SCRIPTS/Notebooks/AdaptiveExperimentation/Ax_MultiObjective.py", line 911, in <module>
    main()
  File "/home/xxx/SCRIPTS/Notebooks/AdaptiveExperimentation/Ax_MultiObjective.py", line 839, in main
    scheduler.run_n_trials(max_trials=5)
  File "/scratch1/xxx/conda/envs/2022_venv/lib/python3.9/site-packages/ax/service/scheduler.py", line 900, in run_n_trials
    for _ in self.run_trials_and_yield_results(
  File "/scratch1/xxx/conda/envs/2022_venv/lib/python3.9/site-packages/ax/service/scheduler.py", line 850, in run_trials_and_yield_results
    while n_remaining_to_run > 0 and self.run(
  File "/scratch1/xxx/conda/envs/2022_venv/lib/python3.9/site-packages/ax/service/scheduler.py", line 960, in run
    existing_trials, new_trials = self._prepare_trials(
  File "/scratch1/xxx/conda/envs/2022_venv/lib/python3.9/site-packages/ax/service/scheduler.py", line 1268, in _prepare_trials
    new_trials = self._get_next_trials(num_trials=n_new) if n_new > 0 else []
  File "/scratch1/xxx/conda/envs/2022_venv/lib/python3.9/site-packages/ax/service/scheduler.py", line 1286, in _get_next_trials
    generator_runs = self._gen_new_trials_from_generation_strategy(
  File "/scratch1/xxx/conda/envs/2022_venv/lib/python3.9/site-packages/ax/service/scheduler.py", line 1341, in _gen_new_trials_from_generation_strategy
    return self.generation_strategy._gen_multiple(
  File "/scratch1/xxx/conda/envs/2022_venv/lib/python3.9/site-packages/ax/modelbridge/generation_strategy.py", line 471, in _gen_multiple
    generator_run = _gen_from_generation_step(
  File "/scratch1/xxx/conda/envs/2022_venv/lib/python3.9/site-packages/ax/modelbridge/generation_strategy.py", line 833, in _gen_from_generation_step
    generator_run = generation_step.gen(
  File "/scratch1/xxx/conda/envs/2022_venv/lib/python3.9/site-packages/ax/modelbridge/generation_node.py", line 167, in gen
    return model_spec.gen(
  File "/scratch1/xxx/conda/envs/2022_venv/lib/python3.9/site-packages/ax/modelbridge/model_spec.py", line 204, in gen
    return fitted_model.gen(**model_gen_kwargs)
  File "/scratch1/xxx/conda/envs/2022_venv/lib/python3.9/site-packages/ax/modelbridge/base.py", line 666, in gen
    base_gen_args = self._get_transformed_gen_args(
  File "/scratch1/xxx/conda/envs/2022_venv/lib/python3.9/site-packages/ax/modelbridge/base.py", line 621, in _get_transformed_gen_args
    optimization_config = t.transform_optimization_config(
  File "/scratch1/xxx/conda/envs/2022_venv/lib/python3.9/site-packages/ax/modelbridge/transforms/standardize_y.py", line 97, in transform_optimization_config
    c.bound = float(
TypeError: only size-1 arrays can be converted to Python scalars
```

Any help is much appreciated.

Thanks very much.

D

**Comment by lena-kashtelyan** [comment]
@dreamoir, I think you did everything correctly and this appears unexpected! We'll look into this, but in the meantime would you mind trying to upgrade Ax to 0.2.5 that will be released imminently (you should be able to try it out starting in a couple of hours) and letting us know whether that fixes this issue? You can also try `Models.MOO_MODULAR` instead of `Models.MOO`, which might help.

**Comment by dreamoir** [comment]
Hi Lena,

Thanks very much for your reply. I have tried using `Models.MOO_MODULAR ` and upgrading to 0.2.5, but get the same error:

```
Traceback (most recent call last):
  File "/home/xxx/SCRIPTS/Notebooks/AdaptiveExperimentation/Ax_MultiObjective.py", line 969, in <module>
    main()
  File "/home/xxx/SCRIPTS/Notebooks/AdaptiveExperimentation/Ax_MultiObjective.py", line 854, in main
    scheduler.run_n_trials(max_trials=5)
  File "/home/xxx/.local/lib/python3.9/site-packages/ax/service/scheduler.py", line 811, in run_n_trials
    for _ in self.run_trials_and_yield_results(
  File "/home/xxx/.local/lib/python3.9/site-packages/ax/service/scheduler.py", line 761, in run_trials_and_yield_results
    while n_remaining_to_run > 0 and self.run(
  File "/home/xxx/.local/lib/python3.9/site-packages/ax/service/scheduler.py", line 871, in run
    existing_trials, new_trials = self._prepare_trials(
  File "/home/xxx/.local/lib/python3.9/site-packages/ax/service/scheduler.py", line 1181, in _prepare_trials
    new_trials = self._get_next_trials(num_trials=n_new) if n_new > 0 else []
  File "/home/xxx/.local/lib/python3.9/site-packages/ax/service/scheduler.py", line 1199, in _get_next_trials
    generator_runs = self._gen_new_trials_from_generation_strategy(
  File "/home/xxx/.local/lib/python3.9/site-packages/ax/service/scheduler.py", line 1257, in _gen_new_trials_from_generation_strategy
    return self.generation_strategy._gen_multiple(
  File "/home/xxx/.local/lib/python3.9/site-packages/ax/modelbridge/generation_strategy.py", line 473, in _gen_multiple
    generator_run = _gen_from_generation_step(
  File "/home/xxx/.local/lib/python3.9/site-packages/ax/modelbridge/generation_strategy.py", line 835, in _gen_from_generation_step
    generator_run = generation_step.gen(
  File "/home/xxx/.local/lib/python3.9/site-packages/ax/modelbridge/generation_node.py", line 165, in gen
    return model_spec.gen(
  File "/home/xxx/.local/lib/python3.9/site-packages/ax/modelbridge/model_spec.py", line 204, in gen
    return fitted_model.gen(**model_gen_kwargs)
  File "/home/xxx/.local/lib/python3.9/site-packages/ax/modelbridge/base.py", line 661, in gen
    base_gen_args = self._get_transformed_gen_args(
  File "/home/xxx/.local/lib/python3.9/site-packages/ax/modelbridge/base.py", line 616, in _get_transformed_gen_args
    optimization_config = t.transform_optimization_config(
  File "/home/xxx/.local/lib/python3.9/site-packages/ax/modelbridge/transforms/standardize_y.py", line 97, in transform_optimization_config
    c.bound = float(
TypeError: only size-1 arrays can be converted to Python scalars

```

Any other suggestions are appreciated.

**Comment by lena-kashtelyan** [comment]
We'll look into this in that case!

**Comment by lena-kashtelyan** [comment]
We're looking into cutting new version now, which should address this.
